config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#home'

  # https://stackoverflow.com/questions/4479233/static-pages-in-ruby-on-rails
  controller :static_pages do
    get :admin
    get :about
    get :contact
    get :help
    get :acknowledgements
    get :streets
    get :sanborn
    get :history
    get :story_intro
    get :illich # Jerry Illich
    get :marietich # Jack Marietich
    get :postira # Postira, Brač Picnics
    get :images
    get :tojson
    get :trials # for development and testing at Heroku. Can delete if no longer used. Delete link in header also
  end

  # get 'otherimages', to: 'static_pages#images' # was images until created. Removed this link

  # get    'stories/index' # why
  get 'stories', to: 'stories#index'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # get   "one_line", to: 'resto_resid_lines#one_line' #, controller: 'resto_resid_lines'
  resources :docs

  resources :all_locations, only: %i[index]

  resources :locations do
    resources :docs # added with polymorphic
    # resources :years # just to see if this would help on allLocations.html.erb. Seems to work without it 2021.07.02
    # https://boringrails.com/articles/hovercards-stimulus/ next three lines. At present, not working
    # member do
    #   get :hovercard
    # end
  end
  get 'addresses', to: 'locations#index'

  # For map in people/show.
  # https://stackoverflow.com/questions/60610788/rails-connecting-to-jbuilder
  resources :people do
    # all default routes are included with this
    resources :locations, only: %i[index], module: :people
    resources :lines, only: %i[index], module: :people
  end

  # https://gorails.com/forum/how-do-i-create-a-delete-button-for-images-uploaded-with-active-storage
  # resources :years # Tried this without all the below commented out and still double GET
  resources :years do
    member do
      delete :delete_image_attachment # I think this is for images added before I started using docs for images
    end

    # Ransack
    collection do
      match 'search', to: 'years#search', via: %i[get post], as: :search
    end
  end
  get 'connections', to: 'years#index'
  get 'summary', to: 'years#summary'
  get 'line', to: 'years#line'
  get 'documents', to: 'years#documents' # Still needed for legacy AWS files

  # get 'search', to: 'years#search' # FIXME Doesn't seem like a good idea to use a general search term for just years. Does it work without this? I think it's in Ransack now

  resources :sources do
    member { delete :delete_image_attachment }
  end
  get 'sources_brief', to: 'sources#index_brief'

  # All links for Historical Streets Los Angeles. FIXME. Can't figure out how to use these with link_to
  direct :historicalla do
    'https://stark-cove-20051.herokuapp.com/'
  end
  direct :historicalla_addresses do
    'https://stark-cove-20051.herokuapp.com/street_list/' # street_list implemented in historicLA since streets goes to crores/streets which is different
  end

  resources :users
  resources :sessions # for logging in. p337
  resources :account_activations, only: %i[edit]
  resources :password_resets, only: %i[new create edit update]
  resources :resto_resid_lines
  resources :lines, controller: 'resto_resid_lines' # alternate /url
  resources :images # do I need this anymore?

  # From Clark, but too crude. See below for what I need to do
  # resources :map
  get 'map', to: 'map#index' # leaftlet version of map

  # The following are for OpenLayers. Some are development
  get 'olMap', to: 'map#olMap' # ol version of map
  get 'openlayers', to: 'map#ol'
  get 'ol', to: 'map#ol'
  get 'olls', to: 'map#ol_layer_switcher'
  get 'layerswitcher', to: 'map#ol_layer_switcher'
  get 'geojson_features', to: 'map#geojson_features'
  get 'geojsonFromFile', to: 'map#geojsonFromFile'
  get 'leafletSelfContained', to: 'map#leaflet_self_contained'
  get 'leafletSelfContainedMapDiv2', to: 'map#leafletSelfContainedMapDiv2'
  get 'allLocations', to: 'locations#allLocations' # had the html.erb in /map but /location seems more logical

  # jBuilder needs the following. FIXME need to see if all of these are still being used
  get 'map/map_data', defaults: { format: 'json' } # using point_data and line_data now. NO, still needed for something.
  get 'map/dot_data', defaults: { format: 'json' }
  get 'map/line_data', defaults: { format: 'json' }
  get 'map/line_point_data', defaults: { format: 'json' } # combining lines and points
  get 'map/point_data', defaults: { format: 'json' }
  get 'locations/allLocations', defaults: { format: 'json' }
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home; end

  def help; end

  def acknowledgements; end

  def about; end

  def contact; end

  def admin; end

  def illich; end

  def marietich; end

  def story_intro; end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_illich_resto_drawing.html.erb
<!-- Live Demo https://getbootstrap.com/docs/5.0/components/modal/#live-demo -->
<!-- with added for modal-body https://getbootstrap.com/docs/5.0/components/modal/#tooltips-and-popovers -->
<!-- Will work this into what I want. Note this is Bootstrap 5 code although I'm still on Bootstap 4. Works so far -->
<!-- Button trigger modal -->
<button class="float-end btn btn-outline-dark m-1" data-toggle="modal" data-target="#illichAd">
  <%= image_tag("https://crores.s3.amazonaws.com/photos/1890-07-14.Iliich_restaurant_ad.png", alt: "Illich adverisement ", height: '236', width: '124') %>
</button>

<!-- Modal and Popover combined.  -->
<div class="modal fade" id="illichAd" tabindex="-1" aria-labelledby="illichAdLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="illichAdLabel">1890 Los Angeles Herald</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-body">
        <%= link_to image_tag("https://crores.s3.amazonaws.com/photos/1890-07-14.Iliich_restaurant_ad.png", alt: "Illich advertisement", height: '872', width: '492'), 'years/44' %>

      </div> <!-- modal-body -->
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
      </div> <!-- modal-footer -->

    </div> <!-- modal-content -->
  </div>
</div>

app/views/static_pages/_illich_resto_former.html.erb
<!-- Live Demo https://getbootstrap.com/docs/5.0/components/modal/#live-demo -->
<!-- with added for modal-body https://getbootstrap.com/docs/5.0/components/modal/#tooltips-and-popovers -->
<!-- Will work this into what I want. Note this is Bootstrap 5 code although I'm still on Bootstap 4. Works so far -->
<!-- Button trigger modal -->
<% resto_image_url = "https://crores.s3.us-west-1.amazonaws.com/Newspaper_articles/1900-Dec-15.Los_Angeles_Times.pI8.Illich_ad.png" %>
<button class="btn btn-outline-dark m-1" data-toggle="modal" data-target="#formerIllichResto">
  <%= image_tag(resto_image_url, alt: "Former Illich resto", width: '208', height: '129') %>
</button>

<!-- Modal and Popover combined.  -->
<div class="modal fade" id="formerIllichResto" tabindex="-1" aria-labelledby="formerIllichRestoLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="formerIllichRestoLabel">1900 Los Angeles Times<br>1901 City Directory: Robert Gordan Proprietor</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-body">
        <%= link_to image_tag(resto_image_url, alt: "Former Illich resto ", width: '416', height: '258'), 'years/xx' %>
      </div> <!-- modal-body -->
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
      </div> <!-- modal-footer -->

    </div> <!-- modal-content -->
  </div>
</div>

app/views/static_pages/home.html.erb
<div class=""> <!-- Was jumbotron with bootstrap 4 -->
  <h1><%= full_title(yield(:title)) %> </h1>

  <h2>
    A project to trace the ownership and locations of Croatian operated restaurants in early Los Angeles.
  </h2>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-5">
        <div id="homepage"> <!-- Can't get this CSS to work. Lines work, but font-size doesn't -->
    <!-- < = link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %> -->

    <p>Alpha (alpha meaning not feature complete. Beta is feature complete, but in test) site. Welcome. Not ready for prime time, but it's up so contributors can see what's going on and so I can see how it works on the web.</p>
    <p>I'm in the process of testing the concept. As of July 2016 I've only entered about 30 percent of the data. But I want to test other aspects before adding more data to make sure it's organized correctly.</p>
    <p>Currently this is a compilation of the data is being used to draw <%= link_to "a map illustrating the location of the people, their restaurants and residences", map_path %>. If you have any questions, comments or suggestions, go to the <%= link_to "Contact page", contact_path %> and email me. I'll be happy to add information to this site.</p>
    <p>Later I plan to open up the database, so others can contribute. I'd like to add photos and other memorabilia to the site.</p>
    <p>You can look at the information, but logging in is adminstrator only for now.</p>
    <p>The navigation links at the top of the page will take you to the information. <b><%= link_to "Connections", summary_path %></b> is the page where the people are connected to the address of the restaurants or residences.</p>
    <p>General sources and methodology of data gathering is discussed on the <b><%= link_to "About page", about_path %></b>. References are generally included in the details of each item under Source. </p>
    <p>If you're looking for the old <b><%= link_to "Keep The Rubber Side Down website", "https://knobby.ws" %></b>, it's been moved <%= link_to "here", "https://knobby.ws" %>, my blog and photo site.</p>
    </div>
  </div>  <!-- col-md-5 home -->
  <div class="col-md-4">
  <figure>
    <%= link_to image_tag("https://crores.s3.amazonaws.com/photos/Restaurant-002.jpg", alt: "Skaric restaurant", height: '400', width: '558'), '#' %> 
    <figcaption class="media-heading">Skarich Restaurant</figcaption>
    </figure>
    <figure>
    <%= link_to image_tag("https://crores.s3.amazonaws.com/photos/1890-07-14.Iliich_restaurant_ad.png", alt: "Illich adverisement ", height: '872', width: '492'), 'years/44' %> 
    <figcaption>1890 Ad From Los Angeles Herald</figcaption>
    </figure>
    </div>
  </div>  <!-- row -->
  </div>  <!-- container-fluid -->
  <div>
    <h4>Trivia</h4>
    <p> According to <%= link_to "this site", "https://esrimedia.maps.arcgis.com/home/webmap/viewer.html?webmap=b41f3711dabb4b7b91e9a2c26cf6a23d" %> 0.06 percent of Los Angeles claims Yugoslavian descent, and Croatia is only a part of former Yugoslavia.</p>
  </div>

  <div class="container-fluid">
    <div class="row">
      <div class="railslogo col-md-4">
         Powered by <%= link_to image_tag("rails-logo.svg", alt: "Rails 5 logo", height: "100", width: "129"), "https://rubyonrails.org/" %>
          <%= link_to "PostGIS", 'https://ngauthier.com/2013/08/postgis-and-rails-a-simple-approach.html' %>
       and <%= link_to "MaptimeLA", 'https://www.meetup.com/MaptimeLA/' %>
       </div>

       <div class="col-md-3">
           <!-- spacing out the flags ? -->
      </div>

     <div class="col-md-3">
         <%= link_to image_tag("croatianFlagWaving.jpg", alt: "Croatian flag", height: '100', width: '93'), 'https://en.wikipedia.org/wiki/Croatia' %>
         <%#= link_to image_pack_tag("croatianFlagWaving.jpg", alt: "Croatian flag", height: '100', width: '93'), 'https://en.wikipedia.org/wiki/Croatia' %> <!-- Error -->
     </div>

     <div class="col-md-3">
         <%= link_to image_tag("usFlagWaving.jpg", alt: "US flag", height: '73', width: '100'), 'https://en.wikipedia.org/wiki/United_States' %>
     </div>

    </div>  <!-- row -->
  </div>   <!-- container-fluid -->
</div> <!-- jumbotron -->

app/views/static_pages/images.html.erb
<div class=" "> <!-- Seems like overkill, but does provide some margins around overall main part of the page -->
	<% provide(:title, "Images") %>
	<!-- <h1>Images</h1> -->
	<div class="container-fluid">

    <figure class="media well">
        <a href="/years/216">
          <img class="media-object media-left" src="https://crores.s3.us-west-1.amazonaws.com/Newspaper_articles/1883%20Sept%2014.%20Los%20Angeles%20Herald.%20Dol.%20Commerial%20Restaurant.png" height="366" width="395">
        </a>
        <figcaption class="media-heading">Sept. 14, 1883. Los Angeles Herald</figcaption>
    </figure>

    <figure class="media well">
      <a href="years/217"><img class="media-object media-left" src="http://crores.s3.amazonaws.com/Newspaper%20articles/1883%20Sept%2014.%20Marietich.%20Queen%20Chop%20House.%20Snippet.png" width="412" height="259" alt="1883 Sept 14. Marietich. Queen Chop House. Snippet"></a>
			<figcaption class="media-heading">Sept. 14, 1883. Los Angeles Herald</figcaption>
    </figure>
		
	  <figure class="media well">
      <%= link_to image_tag("http://crores.s3.amazonaws.com/photos/Restaurant-001.jpg", alt: "Skaric restaurant", height: '400', width: '558'), '#' %>
      <figcaption class="media-heading">Skarich restaurant</figcaption>
		</figure>
	
  </div>
</div>
  

app/views/static_pages/marietich.html.erb
<% provide(:title, 'Jack Marietich') %>
<h1>Jack Marietich</h1>
<div class="fs-5 m-2">
  <p>Following Jack Marietich through the City Directories and other records is a little more difficult than for Jerry Illich. There were only two Illichs in early Los Angeles—Jerry and John. The only complication is that their first initial is J but the spelling of their names was fairly consistent through the years‚ a dropped "l" here and there and mixing up "i" and "l". But in the 19th century there were at least four Marietichs—Jack, Andrew jr (as it was written then), Andrew and James. And a Jacob shows up too, but as far as I can tell that is Jack, but maybe I'll find out differently as more information is gathered. At least two of these are known to have been born in what is now Milna, Brač, Croatia. Brač being an island off the coast from Split.</p>
  <p>As for Jerry Illich, some of the Marietichs came via San Francisco. As we know San Francisco was the port for the Gold Rush which started with the discovery of gold east of San Francisco in 1848 one week before Mexico ceded possession <%= link_to "[*]", "https://en.wikipedia.org/wiki/California" %>. Records from those days are rare particularly since the 1906 earthquake and fire destroyed many of them. But we work with what we have. But I have a longer history with the Marietichs so may have more information. </p>
  <p>The earliest Marietich in California was Jack Marietich's brother, Andrew (<em>Sr</em>). Andrew was born in Milna 15 Aug. 1829 (the <%= link_to "original church record" , 'https://www.familysearch.org/ark:/61903/3:1:3QS7-899X-X9S8-N?i=24&wc=9R2W-166%3A391644801%2C392199001%2C392199002&cc=2040054
https://sg30p0.familysearch.org/service/records/storage/dascloud/das/v2/3:1:3QS7-899X-X9S8-N/dist.jpg?ctx=CrxCtxPublicAccess&header=Content-Disposition&headerValue=attachment%3B%20filename%3Drecord-image_.jpg', target: "_blank" %> shows 15 Aug. 1827), and his obituary states that he immigrated in 1849 (20 years old). But the MyHeritage website has an immigration record from 1888 but maybe he traveled back to Croatia then. More likely he came here young but had the Gold Rush information reached Milna in 1849? Or was 1849 a guess by a relative 40 years later at his death. And 1849 would be more interesting than say 1855. But in any case Andrew was a generation older than Jerry Illich. The first record of Andrew in the United States is the 1861 San Francisco Directory. And Andrew Marieitch <em>sic, but spelled correctly in the Business Directory section</em> has the "Golden Gate Restaurant" at 10 Stewart St. Three other restaurants were operated by Croatians of the 70 listed. He is also a Director in the "Slavonih Ellirih Mutual Benevolent Society" which had been organized November 17, 1857. And he is recorded as operating restaurants at other locations over the years; becoming a citizen and registering to vote in 1868 (age 39). His wife, Agatha Kleiber (Klaiber) had nine children between 1863 and 1874 or later. (Records from then barely recognize that a woman had something to do with children.) Andrew remarried in 1879. I'm mentioning Andrew for a number of reasons: he was a restauranteur, he moved to Los Angeles a few years before his death (presumably retired), two of his daughters married men who would become Los Angeles restauranteurs and lastly he's my great-great grandfather. But now onto Jack Marietich.</p>
  <p>Jack Marietich started in Los Angeles about the same time as Jerry Illich and both are listed in the 1879 Los Angeles City Directory that year. <%= link_to "Illich", "years/1360" %> with a "chop house" at 20 Main and "Giacob" (Jack) <%= link_to "Marietich", "years/1361" %> as a clerk there. No other employees are listed in the directory and no residential addresses are listed for either; although they may lived at the restaurant.</p>
  <p> Two years later in 1881 Marietich has his first restaurant a few doors away at 44 Main St, the <%= link_to "Queen chop house", "http://localhost:3000/years/1323" %> at 44 Main St. in partnership with G. Stuparish (the only time he's showed up). But this time he has a <%= link_to "residential address", "years/1322" %>, 18 Wilmington St, two blocks from his restaurant.</p>
  <p>In the 14 Sept. 1883, the Los Angeles Herald had an announcement of the re-opening of the &ldquo;Queen Chop House&ldquo; by  &ldquo;the popular proprietors, Messrs. J. Marietich & Co., who intend to have the best of everything.&ldquo;</p> He was the proprietor at that location until 1891. The address was 222 N. Main St. which was renumbered to 322 around 1890. In 1892, the restaurant then passed into the hands of his nephew, Andrew, jr and by that time the restaurant was the &ldquo;Old Queen Chop House&ldquo;. He with Peter L Marincovich continued operating the restaurant until <%= link_to "1905", "years/691" %>

  <p>All of Jack Marietich&rsquo;s restaurant and residential <%= link_to "addresses", "people/41" %>  in Los Angeles.</p>
  <hr>
  <%= link_to 'Back to Jerry Illich', 'illich', class: "btn btn-outline-success float-start" %><%= link_to 'Next … TBD', '', class: "btn btn-outline-success float-end" %>
</div> <!-- end fs-5 -->

In 1896 he had a gardener listed on p364 viz

app/views/static_pages/streets.html.erb
<% provide(:title, "Streets and Blocks") %>
<h1>Streets and Blocks</h1>
<div class="container">
<p><em>Some of the details of street name changes are now being tracked in spreadsheet which has yet to be posted</em>. Need to decide whether to use something like Google Docs or a database.</p>
	<p>Some of the street names have changed over the period. Some streets have disappeared and some have appeared. Some north-south streets were renumbered in about 1888–9 [will refine this].</p>
<p>Digits have been used for numbered streets.  That is because I started this project using city directories and they used this convention presumably because it was shorter. For me at least it's slightly easier to visualize using digits too. But the Sanborn maps wrote out the names (1888 and 1894). For example, 1st St vs First Street. I don't know what the official version was (probably wasn't one). Today we would use the written out version at least for small numbers.</p>
    <p> Some addresses are <strong>blocks</strong>, for example, <strong>Mott Block</strong>, which based on looking at maps is what today we would call a building. But to locate them we need a map or street address. Below are links to copied pages of Maxwell's 1887-8 Los Angeles City and County Guide. Maxwell's. <%= link_to image_tag("1887-8 Los Angeles City and County Guide. Maxwell's. Blocks Ad–La. p 639.jpg", alt: "1887 blocks", height: '', width: ''), '#' %> and <%= link_to image_tag("1887-8 Los Angeles City and County Guide. Maxwell's. Blocks La–Wo. p 640.jpg", alt: "1887 blocks", height: '', width: ''), '#' %>	Of interest, two Mott Block listings&mdash;31 S Main St and 14 N Spring St; and Forster Block, 28 S Main St. The latter is maybe of interest because there are listing for the Foster Block &mdash;residence for  <%= link_to "John Bielopero per 1887 Los Angeles City Directory", "locations/25" %>. Are these different buildings or a typo? I hope this will become obvious as I move forward.</p>
    <p><i>Need to make the comments below footnotes to the table</i></p>
    <p><b>Vine</b> ran from 2nd to Jackson. In 1908 was Central Ave. </p>
	<p>or <strong>Main</strong> St in 1886 <%= link_to image_tag("1886–7 Los Angeles City Directory. Bynon. Streets. Johnston–Main. p85.jpg"), '#' %> has 0 at First St and 100 at Market St and also at Requena&mdash;as of July 2016 I don't have a map that can sort this out. It might be possible to sketch out a map based on the description of the street crossings if no satifactory map turns up.
	</p>
  <p>Between 1894 and 1902, the stretch of <strong>Wilmington</strong> between 1st and Commercial became San Pedro. Although still not connecting to section south as it does today. San Pedro from the south continued straight into one block of Wilmington at 2nd. Wilmington only went between 2nd and the intersection of 1st and Los Angeles (five-way intersection). Actually it only shows this way on the 1908 map, so maybe this stretch was always San Pedro and it's an error on the 1908 map. At the moment I'm wondering if both the 1902 and 1908 maps are wrong. Maybe only the section between 1st and Commercial was Wilmington and at some point after 1908 San Pedro was realigned and connected to what had been Wilmington. This eliminated a diagonal for one block and kept San Pedro parallel to Los Angeles for four or five more blocks (connected at about Temple instead of at 1st). </p>
  <H3><BR>Street Name Changes</H3>
    <p>List of resources. How can this be compiled into a searchable map?</p>
    <ul>
      <li><%= link_to "Victorian Downtown Los Angeles", "https://victoriandtla.com/main-street/" %></li>
      <li><%= link_to "Los Angeles in the 1900s&mdash;Streets of a Hundred Years Ago", "https://stevemorse.org/census/changes/LosAngelesChanges2.htm" %> Comprehensive
      <li>https://stevemorse.org/census/changes/LosAngelesChanges2.htm
        <li>
        <li>https://en.wikipedia.org/wiki/Category:Streets_in_Los_Angeles_County,_California. Some of streets have a detailed history
          <li>Haven't explored this yet. https://www.laconservancy.org/resources/guide/historical-research-guide
            <li>References https://morethanredcars.com/?p=57 
              <li>https://articles.latimes.com/2006/dec/10/local/me-then10 Rasmussen 2006 at LATimes and https://articles.latimes.com/1989-07-05/local/me-3186_1_los-angeles-times in 1989
                <li>LAPL resources for property searches https://www.lapl.org/collections-resources/research-guides/history-your-house
                  <li>General LA searches/references https://sites.google.com/site/onlinedirectorysite/Home/usa/ca/losangeles
                    <li>Some history of street naming and references https://www.lapl.org/collections-resources/blogs/central-library/long-and-winding-story-streets-los-angeles
                      <li>
     </ul>                 
  <table class="locations pretty table table-striped table-hover table-responsive">
    <thead>
      <tr><H3><BR>Street Name Changes—<em>This table is archived here for the time being. Above supercedes it.</em></H3></tr>
      <tr>North South streets first. Bunker Hill (need to point out where this is) was leveled in the 1970s and streets could have been moved. Also the 110 and 5 freeways changed things at the west end of this list and between what is now Sunset/Cesar Chavez (then Bellevue/Macy). See also <%= link_to "Sanborn Maps", sanborn_path %> </tr>
    <thead>
       <tr>
        <th>1888 name</th><th>1894 name</th><th>1908</th><th>Today</th>
      </tr>
    </thead>
    <tbody>
    # <tr><td>1888 name</td><td>1894 name</th><th>1908</th><th>Today</td></tr>
    <tr><td>San Fernando</td><td>-</td><td>-</td><th>Spring</td></tr>
       <tr><td></td><td>Reservoir</td><td></td><td>Sunset</td></tr>
      <tr><td>Pearl</td><td>Pearl</td><td> </td><td>Figueroa</td></tr>
      <tr><td>Hope</td><td></td><td> </td><td>Hope</td></tr>
      <tr><td>South Bunker Hill</td><td>Bunker Hill</td><td> </td><td>This was a half block and now doesn't exist</td></tr>
      <tr><td>North Bunker Hill</td><td>North Bunker Hill</td><td> </td><td>May have been realigned. More work needed</td></tr>
      <tr><td>Grand</td><td></td><td> </td><td>Grand</td></tr>
      <tr><td>Olive</td><td></td><td> </td><td>Olive</td></tr>
      <tr><td>Hill</td><td></td><td> </td><td>Hill</td></tr>
      <tr><td>Buena Vista</td><td>Buena Vista</td><td></td><td>Broadway—Between Aliso and Caesar Chavez Broadway was curved to meet Buena Vista and became Broadway. Buena Vista went north from Temple before.</td></tr>
      <tr><td>Fort</td><td>Broadway</td><td></td><td>Broadway</td></tr>
      <tr><td>Spring</td><td></td><td></td><td>Spring</td></tr>
      <tr><td>Main</td><td></td><td></td><td>Main</td></tr>
      <tr><td>Anderson, but didn't go as far south</td><td>Anderson</td><td>Anderson</td><td>Mission</td></tr>
      <tr><td>Amelia</td><td>Amelia</td><td></td><td>N Garey</td></tr>
      <tr><td>Commercial</td><td>same as Commercial</td><td>-</td><td>East of Main. Gone. Temple goes between the first two.</td></tr>
      <tr><td>Requema</td><td>Requema</td><td>Market (betw. Main & Alameda)</td><td>Temple near, but major relignments</td></tr>
      <tr><td>Wilmington</td><td></td><td>San Pedro</td><td>Judge John Aliso for last block</td></tr>
      <tr><td></td><td>Wolfskill Av./Vine</td><td></td><td>Central</td></tr>

</div>

app/views/static_pages/trials.html.erb
<% provide(:title, 'Trials') %>
<h1>Contact</h1>
<p>
 Links to various trials. To remind myself that they exist and as an easier way to test them at Heroku. Some may or may not work. Some of these may have been created with different webpacker set up.
</p>
<p><%= link_to  "Index map, i.e. the current page", map_path, class: "h4"  %>. Uses mapTwo.js and which Leaflet will depend on maps.html.erb CDN and application.js</p>
<p><%= link_to "All Locations", allLocations_path, class: "h4" %> Why hadn't I done this before?</p>
<p><%= link_to  "Map using Open Layer-complete", ol_path %>. Not working. (ol_path)</p>
<p><%= link_to  "GeoJSON Features", geojson_features_path %> Circles and other shapes.</p>
<p><%= link_to  "Leaflet with script on the page.", leafletSelfContained_path %> To eliminate any confusion on Javascript callbacks or whatever. Works as long as div#map</p>
<p><%= link_to  "Leaflet with script on the page.", leafletSelfContainedMapDiv2_path %> Same as previous except div#map_two and DOES NOT WORK</p>
<p><%= link_to  "OpenLayers Basic demo of using map/line_data.geojson", geojsonFromFile_path %>. It works. Superceded by the last item. Was used as a stepping stone</p>
<p><%= link_to  "Map using OpenLayers and LayerSwitcher", olls_path %>. All but timeLine, and it works. from https://github.com/walkermatt/ol-layerswitcher/tree/master/examples</p>
<p><%#= link_to  "Map using OpenLayers next version, map3", map3_path %></p>
<%= form_with(model: @doc) do |form| %>
  <div class="field">
    <%= form.label :TestOfActionText %>
    <%= form.rich_text_area :content %>
  </div>
<% end %>