config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#home'

  # https://stackoverflow.com/questions/4479233/static-pages-in-ruby-on-rails
  controller :static_pages do
    get :admin
    get :about
    get :contact
    get :help
    get :acknowledgements
    get :streets
    get :sanborn
    get :history
    get :story_intro
    get :illich # Jerry Illich
    get :marietich # Jack Marietich
    get :postira # Postira, Brač Picnics
    get :images
    get :tojson
    get :trials # for development and testing at Heroku. Can delete if no longer used. Delete link in header also
  end

  # get 'otherimages', to: 'static_pages#images' # was images until created. Removed this link

  # get    'stories/index' # why
  get 'stories', to: 'stories#index'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # get   "one_line", to: 'resto_resid_lines#one_line' #, controller: 'resto_resid_lines'
  resources :docs

  resources :all_locations, only: %i[index]

  resources :locations do
    resources :docs # added with polymorphic
    # resources :years # just to see if this would help on allLocations.html.erb. Seems to work without it 2021.07.02
    # https://boringrails.com/articles/hovercards-stimulus/ next three lines. At present, not working
    # member do
    #   get :hovercard
    # end
  end
  get 'addresses', to: 'locations#index'

  # For map in people/show.
  # https://stackoverflow.com/questions/60610788/rails-connecting-to-jbuilder
  resources :people do
    # all default routes are included with this
    resources :locations, only: %i[index], module: :people
    resources :lines, only: %i[index], module: :people
  end

  # https://gorails.com/forum/how-do-i-create-a-delete-button-for-images-uploaded-with-active-storage
  # resources :years # Tried this without all the below commented out and still double GET
  resources :years do
    member do
      delete :delete_image_attachment # I think this is for images added before I started using docs for images
    end

    # Ransack
    collection do
      match 'search', to: 'years#search', via: %i[get post], as: :search
    end
  end
  get 'connections', to: 'years#index'
  get 'summary', to: 'years#summary'
  get 'line', to: 'years#line'
  get 'documents', to: 'years#documents' # Still needed for legacy AWS files

  # get 'search', to: 'years#search' # FIXME Doesn't seem like a good idea to use a general search term for just years. Does it work without this? I think it's in Ransack now

  resources :sources do
    member { delete :delete_image_attachment }
  end
  get 'sources_brief', to: 'sources#index_brief'

  # All links for Historical Streets Los Angeles. FIXME. Can't figure out how to use these with link_to
  direct :historicalla do
    'https://stark-cove-20051.herokuapp.com/'
  end
  direct :historicalla_addresses do
    'https://stark-cove-20051.herokuapp.com/street_list/' # street_list implemented in historicLA since streets goes to crores/streets which is different
  end

  resources :users
  resources :sessions # for logging in. p337
  resources :account_activations, only: %i[edit]
  resources :password_resets, only: %i[new create edit update]
  resources :resto_resid_lines
  resources :lines, controller: 'resto_resid_lines' # alternate /url
  resources :images # do I need this anymore?

  # From Clark, but too crude. See below for what I need to do
  # resources :map
  get 'map', to: 'map#index' # leaftlet version of map

  # The following are for OpenLayers. Some are development
  get 'olMap', to: 'map#olMap' # ol version of map
  get 'openlayers', to: 'map#ol'
  get 'ol', to: 'map#ol'
  get 'olls', to: 'map#ol_layer_switcher'
  get 'layerswitcher', to: 'map#ol_layer_switcher'
  get 'geojson_features', to: 'map#geojson_features'
  get 'geojsonFromFile', to: 'map#geojsonFromFile'
  get 'leafletSelfContained', to: 'map#leaflet_self_contained'
  get 'leafletSelfContainedMapDiv2', to: 'map#leafletSelfContainedMapDiv2'
  get 'allLocations', to: 'locations#allLocations' # had the html.erb in /map but /location seems more logical

  # jBuilder needs the following. FIXME need to see if all of these are still being used
  get 'map/map_data', defaults: { format: 'json' } # using point_data and line_data now. NO, still needed for something.
  get 'map/dot_data', defaults: { format: 'json' }
  get 'map/line_data', defaults: { format: 'json' }
  get 'map/line_point_data', defaults: { format: 'json' } # combining lines and points
  get 'map/point_data', defaults: { format: 'json' }
  get 'locations/allLocations', defaults: { format: 'json' }
end

app/models/person.rb
# models/person.rb
class Person < ApplicationRecord
  # include MyDocumentValidator

  has_many :years, dependent: :destroy # destroy gets rid of the years (connection) link if person is deleted which is OK, but the converse is not desirable.
  has_many :locations, through: :years
  belongs_to :doc

  # has_many :doc_people
  # has_many :docs, through: :doc_people
  # has_many :docs, through: :years
  has_many :resto_resid_lines

  # belongs_to :source # FIXME commented so update and save would work, but I think I want this. Location doesn't have this and they are similar in their associations
  has_many_attached :documents # ActiveStorage FIXME legacy
  has_rich_text :content # ActionText
  
  before_save :content_body_to_plain_text

  validates :last_name, presence: true, length: { maximum: 50 }
  validates :given_name, presence: true, length: { maximum: 50 } # ,

  # https://medium.com/swlh/build-a-dynamic-search-with-stimulus-js-and-rails-6-56b537a44579
  include PgSearch::Model
  pg_search_scope :global_search,
      # A list of fields to be searched against.
    against: [:id, :last_name, :given_name, :date_of_birth, :place_of_birth, :date_of_death, :date_of_entry,
         :doe_source, :date_of_citizenship, :notes, :content_plain_text],
    using: {
      tsearch: { prefix: true }
  }

  # uniqueness: {:allow_blank => true} # https://stackoverflow.com/questions/39512689/pguniqueviolation-error-duplicate-key-value-violates-unique-constraint Stopped a testing error (below) by adding this line. Why? But got count error, so maybe this "fix" is making things worse
  # Error:
  # PeopleControllerTest#test_should_create_person:
  # ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_people_on_given_name_and_last_name"
  # DETAIL:  Key (given_name, last_name)=(GivenName1, LastName1) already exists.

  # FIXME. How get from a concern?
  # include LocationsController
  # validates_with MyDocumentValidator # which is in models/concerns/my_document_validator. Does this work?

  # class Profile
  #   def name_split
  #     @split_name ||= fullname.split # @split_name would cache the result so that no need to split the fullname every time
  #   end
  # end

  def self.search(search_people)
    where('last_name  ILIKE ?', "%#{search_people}%")
    # where("given_name ILIKE ?", "%#{search_people}%") #  Doesn't find all with more than one of these
    # where("notes      ILIKE ?", "%#{search_people}%") #
    # where("date_of_birth ILIKE ?", "%#{search_people}%")
    # where("place_of_birth ILIKE ?", "%#{search_people}%")
    # where("date_of_death ILIKE ?", "%#{search_people}%")
    # where("date_of_entry ILIKE ?", "%#{search_people}%")
    # where("doe_source ILIKE ?", "%#{search_people}%")
    # where("date_of_citizenship ILIKE ?", "%#{search_people}%")    #
    # where("source ILIKE ?", "%#{search_people}%")
  end

  def full_name
    # "#{given_name} #{last_name}"
    [given_name, last_name].join(' ') # more Ruby like
  end

  def full_name_id
    "#{given_name} #{last_name} (#{id})"
  end

  def last_first
    "#{last_name}, #{given_name} "
  end

  def last_first_id
    "#{last_name}, #{given_name} (#{id})"
  end

  def full_name_id
    "#{given_name} #{last_name} (#{id})"
  end

  # For next and previous in show. Does this need testing. NOT CRITICAL
  def next
    Person.where(['id > ?', id]).first
  end

  def previous
    Person.where(['id < ?', id]).last
  end

  # Calculate value of content_plain_text by stripping html markup from content
  def content_body_to_plain_text
    self.content_plain_text = content.body.to_plain_text
  end
end

app/controllers/people/lines_controller.rb
# app/controllers/people/lines_controller.rb
# From https://stackoverflow.com/questions/60610788/rails-connecting-to-jbuilder
# Works for both OpenLayers and Leaflet

# From config/routes.rb
# resources :people do
#   resources :locations, only: [:index, :line_loc], module: :people # assuming index is arbitrary and not linked to index page since it's used on show page and line_loc is for another layer
# end

module People
  class LinesController < ApplicationController
    before_action :set_person

    def index
      respond_to do |f|
        f.json
      end
    end

    private

    def set_person
      @person = Person.eager_load(:locations)
                      .find(params[:person_id])
      @locations = @person.locations
    end
  end
end

# https://stackoverflow.com/questions/59548291/rails-passing-variable-to-jbuilder
# For OpenLayers version. Not clear to me why it doesn't work.
# module People
#   class LocationsController
#     # GET /people/1/locations.json
#     def index
#       @person = Person.includes(:locations).find(params[:person_id])
#       @locations = @person.locations
#     end
#   end
# end

app/controllers/people/locations_controller.rb
# app/controllers/people/locations_controller.rb
# From https://stackoverflow.com/questions/60610788/rails-connecting-to-jbuilder
# Works for both OpenLayers and Leaflet

# From config/routes.rb
# resources :people do
#   resources :locations, only: [:index, :line_loc], module: :people # assuming index is arbitrary and not linked to index page since it's used on show page and line_loc is for another layer
# end

module People
  class LocationsController < ApplicationController
    before_action :set_person

    def index
      respond_to do |f|
        f.json
      end
    end

    # # Guessing on this one, trying to connect the dots
    # def line
    #   respond_to do |f|
    #     f.json
    #   end
    # end

    private

    def set_person
      @person = Person.eager_load(:locations)
                      .find(params[:person_id])
      @locations = @person.locations
    end
  end
end

# https://stackoverflow.com/questions/59548291/rails-passing-variable-to-jbuilder
# For OpenLayers version. Not clear to me why it doesn't work.
# module People
#   class LocationsController
#     # GET /people/1/locations.json
#     def index
#       @person = Person.includes(:locations).find(params[:person_id])
#       @locations = @person.locations
#     end
#   end
# end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  # include LocationsController # wrong argument type Class (expected Module)
  helper_method :sort_column, :sort_direction
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    # @people = Person.all
    # @people = Person.order(last_name: :asc) # should sort on index page, but Ransack may be overriding. But isn't hurting anything. Sorting on ID by default.
    # For Sortable columns
    # @people = Person.order(sort_column + " " + sort_direction) # Redundant as it is below

    if params[:search_people]
      @people = Person.search(params[:search_people]).order('given_name ASC') # sorts on first name
    else
      # @people = Person.all
      @people = Person.order(sort_column + ' ' + sort_direction) # Changing from above fixed sorting.Doesn't matter if this is here or not
    end

    # For Stimulus search
    # https://medium.com/swlh/build-a-dynamic-search-with-stimulus-js-and-rails-6-56b537a44579
    if params[:query]
      @people = Person.global_search(params[:query])
    else
      @people = Person.all
    end
    respond_to do |format|
      format.html
      format.json { render json: { people: @people } }
    end
  end

  # GET /people/1
  # GET /people/1.json
  def show; end

  # GET /people/new
  def new
    @person = Person.find_by(id: params[:base_id])&.dup || Person.new # for duplicate
    # repopulateResidResto() # If this is just for the new page, it's not needed. Probably just create and update
  end

  # GET /people/1/edit
  def edit; end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)
    puts @person.last_name
    puts '@person.last_name above. Person.new(person_params).last_name below'
    puts Person.new(person_params).last_name
    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
    # repopulateResidResto() # a new person won't change. Need to go to years
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
    repopulateResidResto() #  updating resto_resid_lines to whatever may have changed due to this change
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
    repopulateResidResto()
  end

  # the following two defs used by map_data.json.jbuilder
  # def line_data()
  #   @where_who_when  =  Years.select("location_id, person_id, ")
  # end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_person
    # byebug
    # binding.pry # works better than byebug?
    @person = Person.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  # people_pkey or pkey, only one is correct
  # TODO is :name needed here
  def person_params
    params.require(:person).permit(:last_name, :given_name, :date_of_birth, :place_of_birth,
                                   :date_of_death, :date_of_entry, :doe_source, :date_of_citizenship, :notes, :croatian, :content, :content_plain_text, :snippet_coords, :doc_id)
  end

  def sort_column
    Person.column_names.include?(params[:sort]) ? params[:sort] : 'last_name'  # Not sure what this needs to be. last_name seemed to make it work. Has to be a column name, not something that's been defined
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
  end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_age.html.erb
<% if @person.date_of_birth? %>
  <span class="text-muted">(<%= (year.year_date - @person.date_of_birth).to_i/365 %>)&nbsp</span>
<% end %>

app/views/people/_bottom_buttons.html.erb
<div id="bottomButtonsPartial" class="row"><div class="col-md-12"><p>&nbsp;</p></div></div> <!--  all of this to get a space between the table and the following -->

<div> <!-- Was also class active -->
  <% if logged_in? %>
    <%= link_to "Duplicate", new_person_path(base_id: @person&.id), class: "btn btn-secondary" %>
    <%= link_to 'Edit this person', edit_person_path(@person), class: "btn btn-primary active"  %>
  <% end %>  
</div>
<br/><br/>
<div class="btn btn-primary"> <!-- Was also class active which is a bit darker-->
  <%= link_to 'Show previous', @person.previous %>&nbsp; &#60; &nbsp;&nbsp;
  <%= link_to 'People List', people_path %> &nbsp;&nbsp;  &#62; &nbsp;
  <%= link_to 'Show next', @person.next %>
</div>

app/views/people/_details_edit.html.erb
<% if logged_in? %>
  <!-- Have this first because of how float-end {right} works. If put all of this in a float-right it gets bigger -->
  <!-- No float down which would be nice as they end up in the wrong place -->
  <span class="btn btn-outline-danger btn-xs float-end"><%= link_to 'Destroy', year, method: :delete, data: { confirm: 'Are you sure you want to delete' } %></span>
  <span class="btn btn-outline-warning btn-xs float-end"><%= link_to 'Edit', edit_year_path(year) %></span>
<% end %>
<span class="btn btn-outline-success btn-xs float-end"><%= link_to 'Details', year %></span>

app/views/people/_form.html.erb
<!-- _form.html.erb used by People: Edit and New —  -->
<%= simple_form_for(@person) do |f| %>
  <%= f.error_notification %>

<!-- Moved this div info to calling form at edit. Not sure which is best, but leaving form cleaner makes some sense -->
  <div class="row col-md-4 col-md-offset-4"> <!-- Makes fields reasonable length -->
    <h3><%= @person.full_name %></h3>
    <%= f.input :given_name %>
    <%= f.input :last_name %>
    <!-- Croatian and related (No for non-Croatian or Croatian but not restaurant related) -->
    <%= f.input :croatian, wrapper: :bootstrap_toggle %> <!-- , wrapper: :bootstrap_toggle works, but default checkbox seems fine https://stackoverflow.com/questions/67613264/how-do-you-write-a-toggle-switch-with-bootstrap-5-and-simple-form#67614414 -->
    <%= f.input :place_of_birth, priority: [ "" ], collection: [ "California", "Croatia", "Brač, Croatia", "Milna, Brač, Croatia", "Postira, Brač, Croatia","Montenegro", "Rijeka, Croatia" ] %>
  </div>
  <%#= f.label :date_of_citizenship %>
  <!-- <div class="col-lg-3"> I think this is to make an indented column -->
    <%= f.input :date_of_birth, include_blank:true, start_year: 1829, end_year: 1930 %>
    <%#= f.date_select :date_of_birth, include_blank:true, start_year: 1829, end_year: 1900 %> <!-- Stacks the 3 fields -->
    <%= f.input :date_of_entry,       include_blank:true, start_year: 1849, end_year: 1930 %>
    <%= f.input :doe_source %>
    <%= f.input :date_of_citizenship, include_blank:true, start_year: 1868, end_year: 1940 %>
    <%= f.input :date_of_death,       include_blank:true, start_year: 1870, end_year: 2000 %>
  <!-- </div> -->
  <!-- Select doc to back this up and add notes. Common the the three models -->
  <!-- !render bookmark -->
  <%= render 'select_docs_notes', form: f %>

  <button type="button" class="btn btn-warning btn-lg active"><%= link_to 'Cancel', :back %></button>
  <button type="button" class="btn btn-primary btn-lg active"><%= f.submit%></button>
<% end %>

app/views/people/_notes.html.erb
<!-- views/people/_notes.html.erb -->
<p>
  <strong>Notes</strong>
  <%= @person.content %>
</p>

<p>
  <% if @person.notes? %> <!-- if @person.notes.length > 1 undefined method `length' for nil:NilClass -->
    <strong>Notes deprecated:</strong>
    <%= @person.notes  %>
  <% end %>
</p>

<p>
  <% if @person.doe_source? %>
    <strong>DoE source:</strong>
    <%= @person.doe_source %>
  <% end %>
</p>
<hr/>
<strong>This page for person ID = <%= @person.id %> updated </strong>
<%#= @person.updated_at.to_formatted_s(:month_year) %>
<%= time_ago_in_words(@person.updated_at) %> ago. But the restaurant and residence information can be more recent.
<hr>
<% if @person.doc_id? %>
  <p>
    <strong>Supporting Doc</strong> (doc_id: <%= @person.doc_id %>): <%#= @person.doc.id %>
<!--can't figure out how to link to the doc, don't want directly to image -->
    <%#= link_to "Supporting Document Info",  %>
    <%#= link_to "Supporting Doc Image", rails_blob_url(@person.doc.image)%>  <!-- undefined method `image' for nil:NilClass -->
   </p>
<% end %> <!-- if @person.doc_id? -->

app/views/people/_person.html.erb
<!-- In doc > show Lists the people that used this document -->
<li id="person-<%= person.id %>"> <!-- Read more of Hartl to find out what this is for -->
  <span class="text-success"><%= person.full_name %></span>
  <% if person.date_of_birth? %>
    <span class="address">,  DoB: <%= person.date_of_birth %></span>
  <% end %>

  <span class="btn btn-outline-success btn-xs"><%= link_to 'Show', person %></span>
  <span class="btn btn-outline-warning btn-xs"><%= link_to 'Edit', edit_person_path(person) %></span>
</li>

app/views/people/_right_col_map.html.erb
<!-- views/people/_right_col_map.html.erb -->
<div id="rightColForMap" class="col-lg-7"> <!-- Was col-lg-8, but want to see listings better -->

  <!-- For the zoom level. Can't get it inside the map -->
  <!-- <div> -->
  <span id="zoom-display-number" class="ol-zoom-in zoom-display-number btn btn-info float-end"></span>
  <!-- </div> -->

  <!-- ol version based on https://stackoverflow.com/questions/59548291/rails-passing-variable-to-jbuilder -->
  <div id="map" class="map-person" data-locations="<%= person_locations_path(@person) %>" data-line="<%= person_lines_path(@person) %>" ></div><!-- data-url isn't just any old variable. data seems to be a key word and what follows it is used as an identifier . -->

  <!-- For popover   -->
  <!-- <div> --> <!-- Was  class="people-show-popup-container", not using div at the moment, but could for fancier formatting -->
    <span class="btn btn-info" id='popover-text'></span> <!-- btn-secondary is gray. Was class was popover-text but trying bootstrap -->
  <!-- </div> -->
  <!-- !render pack olPersonMap -->
  <%= javascript_pack_tag 'olPersonMap' %>
  <span>&nbsp;</span> <!-- Keeps bottom of map from getting buried under footer, why clearfix in footer doesn't do it -->
</div> <!-- id="rightColForMap" class="col-lg-x" -->

app/views/people/_select_docs_notes.html.erb
<!-- Copied from views/layouts/_select_docs_notes.html.erb. Deleted all notes, but look at it if this needs to be changed -->
<!-- Only a partial because was trying to use one for all, but didn't work with people -->
<%= form.association :doc, label_method: :id_page, collection: Doc.all, value_method: :id, label: "Select document(s) that support this" %>
<div class="notes well well-sm">
  <%= form.label :content, "Notes. [Do not attach documents here since already have above. Otherwise end up with multiple copies?]:" %>
  <%= form.rich_text_area :content, rows: 6, value: "Testing, add your own content"  %>
</div>

<!-- Don't show the field if it's empty -->
<% if @person.notes.present? %>
  <div>
    <%= form.label :notes, "Notes (deprecated). Transfer to above" %>
    <%= form.text_area :notes, as: :text, rows: 5 %>
  </div>
<% end %>

app/views/people/_snippet.html.erb
<div class="row">
  <%#= image_tag(@location.doc.image.variant(resize: "400x400")) %> <!-- This works and is operating on the image-->
  <%#= image_tag(@location.doc.image.variant(crop: '400x300+0+0')) %> <!-- Works !! -->
  <%#= image_tag(@location.doc.image.variant(crop: '400x300+400+50')) %> <!-- width x height+x+y top left ref -->
  <%= image_tag(@person.doc.image.variant(crop: '350x40+650+230')) %> <!-- For location/409  hand crafted for Musich although the wrong one-->
</div>>

app/views/people/edit.html.erb
<% provide(:title, 'Edit Person') %>
<h1>Edit: <%= @person.full_name %></h1>

<!-- Copied the two sets of divs from years>edit and just made column narrower, but buttons still didn't sit side by side -->
<div class="row">
  <div class="col-md-6 col-md-offset-3"  id="person_edit_form" > <!--  id="person_edit_form" is for areyousure and not being used at the moment -->
    <!-- !render bookmark -->
    <%= render 'form' %>
  </div>
</div>

app/views/people/index.html.erb
<!-- people/index.html.erb -->
<!-- <p id="notice"><%#= notice %></p> FIXME is there all the time -->
<% provide(:title, 'People') %>
<h1>People (<%= @people.count %>)</h1>

<% if logged_in? %>
	<div class="btn btn-primary" >
		<%= link_to 'New Person', new_person_path %>
	</div>
<% end %>

<!-- See la_hist_street for notes on sources of search -->

<!-- Search may be different for each people, years, and location ?. But it works -->
<!-- This a roll your own solution but only uses Rails, no JavaScript. Including the sorting FIXME http://railscasts.com/episodes/228-sortable-table-columns  Only searches for last name-->
<!-- <%= form_with(url: people_path, method: "get", class:"d-lg-inline-flex mt-2 mt-md-0", id: "search-people-form") do %> -->
  <!-- <%= text_field_tag :search_people,nil, placeholder: "Last name search", class: "form-control mr-sm-2" %> -->
  <!-- <%= button_tag "Search", class: "btn btn-outline-success my-2 my-sm-0", name: nil, data: {disable_with: "<i class='fa fa-spinner fa-spin'></i>"} %> -->
<!-- <% end %> --> <!-- form_with -->
<!-- <%= link_to "Show all", people_path, class: "btn btn-outline-warning my-2 my-sm-0" %> --><!-- Need to hide this when all are showing TODO -->

<!-- Reformatting Stimulus solution from /locations since it's a general solution -->
<!-- Stimulus search -->
<!-- https://medium.com/swlh/build-a-dynamic-search-with-stimulus-js-and-rails-6-56b537a44579 -->
<div class="container">
  <div class="row justify-content-center" data-controller="search-people">
    <div class="col-xs-12 col-sm-6 border rounded-pill border-3 p-2">
      <!-- <h5>Search... <em>on all but ActiveText!</em></h5> -->
      <!-- Can change the fields in model/person.rb -->
      <%= @people.count %> found. 
      <%= form_with(url: people_path, method: :get, class:"d-lg-inline-flex mt-2 mt-md-0", data: {action: "submit->search#submit"}) do |f| %> <!-- Class is mine, not demo and formats the Search button only -->
        <%#= label_tag(:query, "Search for") %>
        <%= text_field_tag :query, params[:query], data: {target: "search.query"}, class: "form-control mr-sm-2", placeholder: "People search:" %>
        <%= submit_tag("Search", class: "btn btn-primary") %>
      <% end %>
      <%= link_to "Show all", people_path, class: "btn btn-outline-warning my-2 my-sm-0" %> <!-- Need to hide this when all are showing TODO -->
    </div>
  </div>
</div>
<br>

<!-- table table-striped table-hover table-responsive - - Losses vertical centering -->
<table class="people pretty table table-striped table-hover table-responsive">
  <thead>
    <tr class="">
      <th class="text-right"><%= sortable "id" , "ID" %></th>
      <th class="text-right"><%= sortable "given_name", "First" %></th>
      <th><%= sortable "last_name" , "Last" %></th>
      <th><%= sortable "date_of_birth", "Birth Date and Place" %></th>
      <th><%= sortable "date_of_entry", "Entry Date" %></th>
      <th><%= sortable "date_of_death", "Died" %></th>
      <th><%= sortable "notes" %></th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <%# for person in @people.order(:last_name) %>   <!-- .order(:last_name) does not sort . Sorting done in controller -->
  <% @people.each do |person| %>
  <!-- Would like the number of connections for each entry FIXME -->
  <tbody>
      <tr class="people">
        <td class="text-right"><%= person.id %></td>
        <td class="text-right"><%= person.given_name %></td>
        <td class="last-name" ><%= person.last_name %></td>
        <td>                   <%= person.date_of_birth %><br/><br/><%= person.place_of_birth %></td>
        <td>                   <%= person.date_of_entry %></td>
        <td>                   <%= person.date_of_death %></td>
        <td>                   <%= person.notes %></td> <!-- .truncate(10) Doesn't work here -->
        <td><%= link_to 'Show details', person %></td>
        <% if logged_in? %>
          <td><%= link_to 'Edit', edit_person_path(person) %></td>
          <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
  </tbody>
  <% end %>
</table>