config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#home'

  # https://stackoverflow.com/questions/4479233/static-pages-in-ruby-on-rails
  controller :static_pages do
    get :admin
    get :about
    get :contact
    get :help
    get :acknowledgements
    get :streets
    get :sanborn
    get :history
    get :story_intro
    get :illich # Jerry Illich
    get :marietich # Jack Marietich
    get :postira # Postira, Brač Picnics
    get :images
    get :tojson
    get :trials # for development and testing at Heroku. Can delete if no longer used. Delete link in header also
  end

  # get 'otherimages', to: 'static_pages#images' # was images until created. Removed this link

  # get    'stories/index' # why
  get 'stories', to: 'stories#index'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # get   "one_line", to: 'resto_resid_lines#one_line' #, controller: 'resto_resid_lines'
  resources :docs

  resources :all_locations, only: %i[index]

  resources :locations do
    resources :docs # added with polymorphic
    # resources :years # just to see if this would help on allLocations.html.erb. Seems to work without it 2021.07.02
    # https://boringrails.com/articles/hovercards-stimulus/ next three lines. At present, not working
    # member do
    #   get :hovercard
    # end
  end
  get 'addresses', to: 'locations#index'

  # For map in people/show.
  # https://stackoverflow.com/questions/60610788/rails-connecting-to-jbuilder
  resources :people do
    # all default routes are included with this
    resources :locations, only: %i[index], module: :people
    resources :lines, only: %i[index], module: :people
  end

  # https://gorails.com/forum/how-do-i-create-a-delete-button-for-images-uploaded-with-active-storage
  # resources :years # Tried this without all the below commented out and still double GET
  resources :years do
    member do
      delete :delete_image_attachment # I think this is for images added before I started using docs for images
    end

    # Ransack
    collection do
      match 'search', to: 'years#search', via: %i[get post], as: :search
    end
  end
  get 'connections', to: 'years#index'
  get 'summary', to: 'years#summary'
  get 'line', to: 'years#line'
  get 'documents', to: 'years#documents' # Still needed for legacy AWS files

  # get 'search', to: 'years#search' # FIXME Doesn't seem like a good idea to use a general search term for just years. Does it work without this? I think it's in Ransack now

  resources :sources do
    member { delete :delete_image_attachment }
  end
  get 'sources_brief', to: 'sources#index_brief'

  # All links for Historical Streets Los Angeles. FIXME. Can't figure out how to use these with link_to
  direct :historicalla do
    'https://stark-cove-20051.herokuapp.com/'
  end
  direct :historicalla_addresses do
    'https://stark-cove-20051.herokuapp.com/street_list/' # street_list implemented in historicLA since streets goes to crores/streets which is different
  end

  resources :users
  resources :sessions # for logging in. p337
  resources :account_activations, only: %i[edit]
  resources :password_resets, only: %i[new create edit update]
  resources :resto_resid_lines
  resources :lines, controller: 'resto_resid_lines' # alternate /url
  resources :images # do I need this anymore?

  # From Clark, but too crude. See below for what I need to do
  # resources :map
  get 'map', to: 'map#index' # leaftlet version of map

  # The following are for OpenLayers. Some are development
  get 'olMap', to: 'map#olMap' # ol version of map
  get 'openlayers', to: 'map#ol'
  get 'ol', to: 'map#ol'
  get 'olls', to: 'map#ol_layer_switcher'
  get 'layerswitcher', to: 'map#ol_layer_switcher'
  get 'geojson_features', to: 'map#geojson_features'
  get 'geojsonFromFile', to: 'map#geojsonFromFile'
  get 'leafletSelfContained', to: 'map#leaflet_self_contained'
  get 'leafletSelfContainedMapDiv2', to: 'map#leafletSelfContainedMapDiv2'
  get 'allLocations', to: 'locations#allLocations' # had the html.erb in /map but /location seems more logical

  # jBuilder needs the following. FIXME need to see if all of these are still being used
  get 'map/map_data', defaults: { format: 'json' } # using point_data and line_data now. NO, still needed for something.
  get 'map/dot_data', defaults: { format: 'json' }
  get 'map/line_data', defaults: { format: 'json' }
  get 'map/line_point_data', defaults: { format: 'json' } # combining lines and points
  get 'map/point_data', defaults: { format: 'json' }
  get 'locations/allLocations', defaults: { format: 'json' }
end

app/models/doc.rb
# models/doc.rb
class Doc < ApplicationRecord
  has_one_attached :image # Active Storage
  # puts "XXXX models/doc:4. @doc: #{@doc}." # doc undefined on edit and show . @doc is nil on show and edit # popped up on an error check and not sure I need this, was debugging I assume
  # sap @doc # super_awesome_print out to iTerm. for debugging issues with metadata # development only. Error at heroku
  before_save :content_body_to_plain_text
  after_save_commit :analyze_metadata_now # same as :analyze_metadata_now, [ on: :create, on: :update ] # # see def below for explanation and link # This now makes sure metadata is created correctly ## after_commit may be deprecated
  belongs_to :source

  # Are the following three handled by …able? I think so since that's what Rails Guides Active Records basics has
  # Will this prevent accidentally deleting a doc with references?
  has_many :locations
  has_many :people
  has_many :years # this works for one doc per year and cloned for people and locations, but not needed to add doc??
  # has_and_belongs_to_many :years
  # has_and_belongs_to_many :people
  # has_and_belongs_to_many :locations

  has_rich_text :content # Action Text. This is for notes but there is no content in the table

  # The following may or may not work FIXME

  # Validate attachment in Active Storage using gem 'active_storage_validations'  https://github.com/igorkasyanchuk/active_storage_validations
  validates :image, attached: true, content_type: [:png, :jpg, :jpeg] # , :pdf, :heic , message: "Apparently HEIC not supported." # added last two since I want them, vips supports them, so should work? HEIC causes an error, but I don't think it's this that's checking. Gives generic message
  # validates :image, presence: true # , uniqueness: true # do upload title page twice #TypeError at doc.save with uniqueness?
  validates :page_no, uniqueness: { scope: [:source_id], message: '. Already a doc for this page number for this source' } # SWAG. Doesn't work right if add , presence: true. Says needs page_no even if has one, but OK if separate below.
  validates :page_no, presence: true # Turned off to see if would do doc.image.metadata. Yes on re-edit

  # validates :source_id, uniqueness: { scope: [:page_no], message: '. This page already entered for this directory' } # May not work for items that aren't city directories. Probably simplier syntax for this situation https://stackoverflow.com/questions/3276110/rails-3-validation-on-uniqueness-on-multiple-attributes Screwed up metadata creation FIXME. Readd when fix that problem

  # For Ransacker to sort on page no. correctly. Does it work? No: Need to sort character varying, this is for integer
  # ransacker :page_no do
  #  Arel.sql("to_char(page_no, '9999999')")
  # end

  # https://medium.com/swlh/build-a-dynamic-search-with-stimulus-js-and-rails-6-56b537a44579
  include PgSearch::Model
  pg_search_scope :global_search,
      # A list of fields to be searched against.
      against: [:id, :original_url, :basename, :notes, :content_plain_text],
    using: {
      tsearch: { prefix: true }
  }

  # Calculate value of content_plain_text by stripping html markup from content
  def content_body_to_plain_text
    self.content_plain_text = content.body.to_plain_text
  end

  def doc_source_page
    "#{page} #{basename} [page basename as test]"
  end

  def year_page
    [source.cover_year, page_no].join(' ') # more Ruby like
  end

  def year_name_page # 949ms and needs id
    "#{source.try(:cover_year)} #{source.try(:name)}. p#{page_no}"
  end

  def year_name_page_notes # a bit unwieldly but it helps for selecting the oc
    "#{source.try(:cover_year)} #{source.try(:name)}. p#{page_no}. #{notes}"
  end

  def id_page_year_name__notes_content # takes 3 seconds to create this using in years>new and probably other places
    "#{id}. #{page_no}. #{source.try(:cover_year)} #{source.try(:name)}. #{notes}. #{content}"
  end

  def id_page # fast, but would like more info. Try for a bit to see if it helps with buttons not working
    "#{id}. #{page_no}"
  end

  def id_page_content # Overall  3370ms. Hard to read, because trix.
    "#{id}. #{page_no}. #{content}"
  end

  # def page_int # trying for sorting in sources>show. Couldn't access this variable
  #    page_no.to_i # "#{page_no.to_i}"
  # end

  def page_year_name__notes_content # a bit unwieldly but it helps for selecting the doc. Changed to above when too many duplicate address numbers
    "#{page_no}. #{source.try(:cover_year)} #{source.try(:name)}. #{notes}. #{content}" # Shows the formatting for trix in the drop down menu
  end

  def test_source_id_page_no
    "#{source_id}. #{page_no}"
  end

  # For next and previous in show.
  def next
    Doc.where(['id > ?', id]).first
  end

  def previous
    Doc.where(['id < ?', id]).last
  end

  # The last doc, i.e., highest numerical id. The previous about is just that. Use occasionally when adding docs to find out where I am
  def last
    Doc.last
  end

  # https://blog.eq8.eu/til/image-width-and-height-in-rails-activestorage.html
  # Can't seem to access this, but can access them. See doc>show
  def height
    image.metadata['height']
  end

  def width
    image.metadata['width']
  end

  # private # get an error if make private NO. Get error after using once; now seems to work. Have to restart server
  # Sometimes docs are created with incomplete metadata, this forces it to be done. Dimensions and 'analyzed' are missing
  def analyze_metadata_now
    puts "X X X X  models/doc:106. image.to_yaml: #{image.to_yaml}" # Debugging. not activated on show as expected. object on update # image.class: #{image.class}.  ActiveStorage::Attached::One and is the first field of .to_yaml
    # puts "XXXX models/doc:88. sap image below YYYYY"
    sap image # Debugging(super_awesome_print). #<ActiveStorage::Attached::One:0x00007fea7e0d4178 @name="image", @record=#<Doc id: 631, source_id: 49, page_no: "262", original_url: nil, basename: "1890–1 Los Angeles and Orange County Business Dire...", created_at: "2021-05-28 05:42:10", updated_at: "2021-05-28 05:42:10", notes: nil, snippet_coords: nil>>
    begin
      image.analyze # if image.attached? # errors on image if can't find, so the if is ignored anyway
    rescue
      puts " XX X X  models/doc:112. image.to_yaml. image couldn't be analyzed X X X X. Rescued from image.analyze"
    end
  end
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  before_action :set_doc, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction

  # GET /docs
  # GET /docs.json
  def index
    # @docs = Doc.all # default
    # @docs = Doc.order(id: :asc) # initial sort on load.
    @q = Doc.ransack(params[:q])
    @docs = @q.result.includes(:source) # this allows associations in ransack

    # For Stimulus search
    # https://medium.com/swlh/build-a-dynamic-search-with-stimulus-js-and-rails-6-56b537a44579
    # Fields searched are set in doc.rb
    if params[:query]
      @docs = Doc.global_search(params[:query])
    else
      @docs = Doc.all
    end
    respond_to do |format|
      format.html
      format.json { render json: { docs: @docs } }
    end

  end

  # GET /docs/1
  # GET /docs/1.json
  def show
    # @source.doc = Naturalsorter::Sorter.sort(@source.docs) # SWAG error
  end

  # GET /docs/new
  def new
    @doc = Doc.new
  end

  # GET /docs/1/edit
  def edit; end

  # POST /docs
  # POST /docs.json
  def create
    # https://guides.rubyonrails.org/active_storage_overview.html#attaching-files-to-records Next 3 lines to see if fixes metadata. Same with these three lines or the longer respond_to below
    # doc = Doc.create!(doc_params)
    # session[:doc_id] = doc.id
    # redirect_to doc

    @doc = Doc.new(doc_params)
    respond_to do |format|
      if @doc.save
        format.html { redirect_to @doc, notice: 'Doc was successfully created.' }
        format.json { render :show, status: :created, location: @doc }
      else
        format.html { render :new }
        # format.html { render :edit } #Broke refresh to get metadaa
        format.json { render json: @doc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /docs/1
  # PATCH/PUT /docs/1.json
  def update
    respond_to do |format|
      if @doc.update(doc_params)
        format.html { redirect_to @doc, notice: 'Doc was successfully updated.' }
        format.json { render :show, status: :ok, location: @doc }
      else
        format.html { render :edit }
        format.json { render json: @doc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /docs/1
  # DELETE /docs/1.json
  def destroy
    @doc.destroy
    respond_to do |format|
      format.html { redirect_to docs_url, notice: 'Doc was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_doc
    @doc = Doc.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def doc_params
    params.require(:doc).permit(:source_id, :page_no, :image, :original_url, :basename, :notes,
                                :content, :content_plain_text, :snippet_coords)
  end

  def sort_column
    Doc.column_names.include?(params[:sort]) ? params[:sort] : 'year_page' # it does matter what this last field is. Where is default sort set?
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
  end
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/views/docs/_doc.html.erb
<!-- rendered from sources/show -->
<li>
  <%#= doc.id %> <%= doc.content %> (p. <%= doc.page_no %>)
  <span class="btn btn-outline-success btn-xs"><%= link_to 'Show', doc %></span>
  <span class="btn btn-outline-warning btn-xs"><%= link_to 'Edit', edit_doc_path(doc) %></span>
</li>

app/views/docs/_form.html.erb
<!-- app/views/docs/_form.html.erb. Used by docs/new /edit-->
<div> <!--  data-controller="get-filename" For stimulus -->
  <%= simple_form_for @doc do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%#= f.input :source %>
      <!-- From person, use as model -->
      <%#= form.association :person, label: "Name of the Person", label_method: :full_name_id, collection: Person.all.order(:last_name).order(:given_name), value_method: :id, include_blank: true %>

      <%= f.association :source, label: "Title of directory or census (ID)", label_method: :year_name_id, collection: Source.all.order(:cover_year).order(:name), value_method: :id, include_blank: true %>
      <%#= collection_select(:source, :year_name, Source.all.order(:cover_year).order(:name), :id, :year_name, include_blank: true ) %>

      <!-- <%= f.input :page_no %>  All the old entries show which I don't want to change to  -->

      <%= f.input :page_no, label: 'Page no.', error: 'Page no. is mandatory, please specify one', label_html: { class: 'form-inputs well well-sm'} %> <!-- , maxlength: 5 no effect. Trying placeholder to get rid of suggested old numbers didn't help size: "2x1", didn't help with size-->

       <div>
        <%= f.label :image, "Select document or image that support this information." %>
        <%= f.file_field :image %> <!-- , 'data-target-get-filename' => "name" Stimulus I think data-target-get_filename and didn't implement? , direct_upload: true  Don't understand what direct_upload is vs whatever else might happen, but got an error, so probably haven't set that up --> 
      </div>

      <div class="notes well well-sm">
        <%= f.label :content, "Notes (generally writing first last even though entry is last first) [Do not attach documents here since already have above. Otherwise end up with multiple copies?]:" %>
        <%= f.rich_text_area :content, rows: 6 %>
      </div>
      <% if @doc.notes? %>
        <div class="form-inputs well well-sm ">
          <%= f.label :notes, " Deprecated? [leaving in form so can copy to above as needed]:" %>
          <%= f.text_area :notes, rows: 5 %> <!-- , size: "5x5" is cols x rows Didn't change width-->
        </div>
      <% end %>

    </div> <!-- class="form-inputs" -->

    <!-- <button type="button" class="btn btn-primary btn-lg active"><%#= f.submit "Create/Update Doc" %></button> -->
    <button type="button" class="btn btn-primary btn-lg active"><%= f.submit data: { disable_with: false } %></button>
    <!-- <div class="form-actions"><%#= f.button :submit %></div> -->
  <% end %> <!-- simple_form_for -->
</div>

app/views/docs/_new_doc_button.html.erb
<% if logged_in? %>
  <div class="row">
    <div class="btn btn-primary col-md-3"> <%= link_to 'Add New Doc', new_doc_path %> </div>
  </div>
<% end %>

app/views/docs/edit.html.erb
<h1>Editing Doc</h1>

<!-- !render bookmark -->
<%= render 'form', doc: @doc %>

<%= link_to 'Show', @doc %> |
<%= link_to 'Back', docs_path %>

app/views/docs/index.html.erb
<p id="notice"><%= notice %></p>
<% provide(:title, 'Docs') %>
<h1>Docs  (<%= @docs.count %>)</h1>
<!-- <ul id="docs"><%#= render @docs %></ul> A demo of https://guides.rubyonrails.org/working_with_javascript_in_rails.html#a-simple-example -->
<!-- !render bookmark -->
<%= render 'new_doc_button' %>
  
<!-- Begin Ransack search form. Couldn't format with Bootstrap, so went with Stimulus. -->
  <!-- <div class="container">
    <%= search_form_for @q do |f| %>
      <div class="col-md-4">
        <%= f.text_field :source_cover_year_or_basename_or_notes_or_content_plain_text_cont, class: "form-control search-field", placeholder: "Search for title, notes, etc. " %>
      </div>
      <div class="col-md-2 col-md-offset-1 form-actions">
        <%= f.submit "Search", class: "btn btn-success" %>
      </div>
      <div class="btn btn-primary col-md-2">
        <%= link_to 'Show all docs', docs_path %>
      </div>
    <% end %>
  </div>  -->
<!-- end ransack search and new -->

<!-- Stimulus search -->
<!-- https://medium.com/swlh/build-a-dynamic-search-with-stimulus-js-and-rails-6-56b537a44579 -->
<div class="container">
  <div class="row justify-content-center" data-controller="search-docs">
    <div class="col-xs-12 col-sm-6 border rounded-pill border-3 p-2">
      <!-- Can change the fields in model/doc.rb -->
      <%= @docs.count %> found. 
      <%= form_with(url: docs_path, method: :get, class:"d-lg-inline-flex mt-2 mt-md-0", data: {action: "submit->search#submit"}) do |f| %> <!-- Class is mine, not demo and formats the Search button only -->
        <%= text_field_tag :query, params[:query], data: {target: "search.query"}, class: "form-control mr-sm-2", placeholder: "Docs search..." %>
        <%= submit_tag("Search", class: "btn btn-primary") %>
      <% end %>
      <%= link_to "Show all", docs_path, class: "btn btn-outline-warning my-2 my-sm-0" %> <!-- Need to hide this when all are showing TODO -->
    </div>
  </div>
</div>
<br>

<table class="years pretty table table-striped table-hover table-responsive">
  <thead>
    <tr>
      <th><%= sort_link(@q, :id, "ID") %></th>
      <th><%= sort_link(@q, :source_cover_year, "Source") %></th> <!-- Want this sorted by year_name and then page number FIXME. not working-->
      <th><%= sort_link(@q, :page_no, "Page no.") %></th>
      <!-- <th>Original url</th> Or shorten if want to see it-->
      <% if logged_in? %>
        <th><%= sort_link(@q, :basename, "Basename") %></th>
      <% end %>
      <th>Notes<% if logged_in? %> <em>, i.e., content</em> <% end %></th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @docs.each do |doc| %>
      <tr>
        <td><%= doc.id %></td>
        <td><%= doc.source.try(:year_name) %></td> 
        <td><%= doc.page_no.to_i %></td> <!-- .to_1 doesn't help sort -->
        <!-- <td><%#= doc.original_url %></td> -->
        <% if logged_in? %> 
          <td><%= doc.basename %></td>
        <% end %> 
        <td><%= doc.content %></td>
        <!-- <td><%#= image_tag doc.image %></td>  --><!-- Can't resolve image into URL: to_model delegated to attachment, but attachment is nil.  w/o image_tag #<ActiveStorage::Attached::One:0x00007f93dd8a84c8> -->
        <td><img class="media-object" src="<%= doc.image %>" height="50" width="50"></td> <!-- image doesn't show -->
        <td><%= link_to 'Show', doc %></td>
        <td><%= link_to 'Edit', edit_doc_path(doc) %></td>
        <td><%= link_to 'Destroy', doc, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!-- !render bookmark -->
    <%= render 'new_doc_button' %>

app/views/docs/new.html.erb
<!-- <p id="notice"><%= notice %> </p> Duplicate ?-->
<% provide(:title, 'New Doc') %>
<h1>New Doc</h1>

<!-- !render bookmark -->
<%= render 'form', doc: @doc %>

<%= link_to 'Back', docs_path %>

app/views/docs/show.html.erb
<!--app/views/docs/show.html.erb -->
<!-- <p id="notice"><%#= notice %></p> --> <!-- Already in /layout somewhere, although this one is formatted better -->
<% new_title = "#{@doc.source.cover_year} p#{@doc.page_no}"  %>
<%= provide(:title, new_title) %>
<div class="row">
  <div class="col">
    <p>
      <strong>Source</strong>:
      <strong><%= link_to @doc.source.year_name, @doc.source %></strong>.  <!-- ID: <%#= link_to @doc.source_id, @doc.source %> -->
    </p>

    <% if @doc.source.effective_date? %>
      <p>
        <strong>Effective date:</strong>
        <%= @doc.source.effective_date.strftime('%Y' ' ' '%b' ' ' '%-d')%> <!-- strftime("%d %b %Y")  -->
      </p>
    <% end %>

    <p>
      <strong>Page no.</strong>
      <%= @doc.page_no %>
    </p>

     <% if @doc.original_url? %>
      <p>
        <strong>Original source:</strong>
        <%= @doc.original_url %>
      </p>
    <% end %>

    <!-- <p> I was doing this manually but ActiveStorage does it anyway
      <strong>Title of file on my computer:</strong>
      <%#= @doc.basename %>
    </p> -->

    <p>
      <strong>Original filename:</strong>
      <%= @doc.image.attached? ? @doc.image.filename : "Doc missing"%>
      <% if @doc.basename? %>
       <br>&nbsp;&nbsp;&nbsp;<strong>and (Originally added manually)</strong> <%= @doc.basename %>
      <% end %>
    </p>

    <p>
      <strong>Notes</strong>
      <%= @doc.content %>
    </p>

    <p>
      <strong>Notes Plain Text for dev: </strong>
      <%= @doc.content_plain_text %>. or <%#= @doc.content.body.to_plain_text %> FIXME
    </p>

    <% if @doc.notes? %>
      <p>
        <strong>Notes</strong> (Deprecated):
        <%= @doc.notes %>
      </p>
    <% end %>

    <p>
      <!-- <strong>Updated</strong> <%#= @doc.updated_at.strftime('%d' ' ' '%b' ' ' '%Y'', ' '%H'':''%H ''%Z') %> -->
      <strong>Updated</strong> <%= time_ago_in_words(@doc.updated_at) %> ago.
    </p>

    <!-- Where doc is used. Used to help to confirm data entry which is why a "popup" like for each would be nice. Can just go through them more quickly than having to create a new page for each one. But complicated by how the lists are created-->
    <h4>What links to this doc:</h4>

    <ol class="years">
      <% if @doc.years.count > 0 %>
        <%= turbo_frame_tag :index do %>
         <h5>Connections <span class="text-secondary"> (Name on doc).</span>:</h5>
          <!-- Every use of this document in the years database -->
          <!-- The format is created by the views/years/_year.html.erb by some kind of magic -->
          <!-- !render bookmark -->
          <%= render @doc.years %> 
         <% end %> <!-- turbo_frame_tag years -->
         <%= render 'turbo_years' %>
       <% end %>
        <% if @doc.people.count > 0 %>
          <br>
          <h5>People:</h5>
          <!-- !render bookmark -->
          <%= render @doc.people %>
        <% end %>
        <% if @doc.locations.count > 0 %>
          <br>
          <h5>Locations:</h5>
          <!-- !render bookmark -->
          <%= render @doc.locations %>
        <% end %>
        <br>
      </ol>
      <div>
        <%= link_to 'Previous document', @doc.previous, class: "btn btn-outline-info" %> &nbsp;  &#60; &nbsp;
        <% if logged_in? %>
          <%= link_to 'Edit', edit_doc_path(@doc), class: "btn btn-success" %>
          <%= link_to 'Back to all Docs', docs_path, class: "btn btn-primary" %>
          <%#= link_to "Duplicate", new_doc_path(base_id: @doc&.id), class: "btn btn-warning" %> <!-- Didn't work -->
          <%= link_to 'New doc', new_doc_path, class: "btn btn-success" %>
        <% end %>
        &nbsp;  &#62; &nbsp; <%= link_to 'Next document', @doc.next, class: "btn btn-outline-info" %>
        <% if logged_in? %>
          &nbsp;  &nbsp; <%= link_to 'Last document', @doc.last, class: "btn btn-outline-dark" %>
        <% end %>
      </div>  <!-- class="btn btn-primary" -->
    </div> <!-- col -->
    <div class="col">

    </div>
  </div> <!-- row and col -->
<br> <!-- to put a space above image -->
<div>
  <!-- Second column for images LEAVE IN LINE FOR THIS NOT THAT MUCH INFO-->
  <!-- <div class="col-lg-7 media media-right"> -->
  <% if @doc.image.attached? %>
    <!-- <% if @doc.image.analyzed? %>
    <% else %>
      <p id="error_explanation"><strong>Refresh page or Edit and resave because doc.image.metadata not created. These tests aren't working quite right because the metadata is in the db. Must be a timing thing.</strong></p>
    <% end %> -->
    <%= image_tag @doc.image %>
  <% else %>
    <p><i>No image uploaded via Active Storage</i></p>
  <% end %> <!-- extra div below  col-lg-7 media media-right-->
</div>
  <!-- </div>   --><!-- class="col-lg-7 media media-right -->
<!-- </div>  --><!-- end row OR the whole thing -->

<!--  all of this to get a space between the table and the following -->
<!-- <div class="row"><div class="col-md-12"><p>&nbsp;</p></div></div>
<div class="row"><div class="col-md-12"><p>&nbsp;</p></div></div> -->

<div>
  <% if logged_in? %>
    <%= link_to 'Previous item', @doc.previous, class: "btn btn-outline-info" %> &nbsp;  &#60; &nbsp;
  <% end %>
  <%= link_to 'Back to all Docs', docs_path, class: "btn btn-primary" %>
  <% if logged_in? %>
     &nbsp;  &#62; &nbsp; <%= link_to 'Next item', @doc.next, class: "btn btn-outline-info" %>
  <% end %>
</div>