config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#home'

  # https://stackoverflow.com/questions/4479233/static-pages-in-ruby-on-rails
  controller :static_pages do
    get :admin
    get :about
    get :contact
    get :help
    get :acknowledgements
    get :streets
    get :sanborn
    get :history
    get :story_intro
    get :illich # Jerry Illich
    get :marietich # Jack Marietich
    get :postira # Postira, Brač Picnics
    get :images
    get :tojson
    get :trials # for development and testing at Heroku. Can delete if no longer used. Delete link in header also
  end

  # get 'otherimages', to: 'static_pages#images' # was images until created. Removed this link

  # get    'stories/index' # why
  get 'stories', to: 'stories#index'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # get   "one_line", to: 'resto_resid_lines#one_line' #, controller: 'resto_resid_lines'
  resources :docs

  resources :all_locations, only: %i[index]

  resources :locations do
    resources :docs # added with polymorphic
    # resources :years # just to see if this would help on allLocations.html.erb. Seems to work without it 2021.07.02
    # https://boringrails.com/articles/hovercards-stimulus/ next three lines. At present, not working
    # member do
    #   get :hovercard
    # end
  end
  get 'addresses', to: 'locations#index'

  # For map in people/show.
  # https://stackoverflow.com/questions/60610788/rails-connecting-to-jbuilder
  resources :people do
    # all default routes are included with this
    resources :locations, only: %i[index], module: :people
    resources :lines, only: %i[index], module: :people
  end

  # https://gorails.com/forum/how-do-i-create-a-delete-button-for-images-uploaded-with-active-storage
  # resources :years # Tried this without all the below commented out and still double GET
  resources :years do
    member do
      delete :delete_image_attachment # I think this is for images added before I started using docs for images
    end

    # Ransack
    collection do
      match 'search', to: 'years#search', via: %i[get post], as: :search
    end
  end
  get 'connections', to: 'years#index'
  get 'summary', to: 'years#summary'
  get 'line', to: 'years#line'
  get 'documents', to: 'years#documents' # Still needed for legacy AWS files

  # get 'search', to: 'years#search' # FIXME Doesn't seem like a good idea to use a general search term for just years. Does it work without this? I think it's in Ransack now

  resources :sources do
    member { delete :delete_image_attachment }
  end
  get 'sources_brief', to: 'sources#index_brief'

  # All links for Historical Streets Los Angeles. FIXME. Can't figure out how to use these with link_to
  direct :historicalla do
    'https://stark-cove-20051.herokuapp.com/'
  end
  direct :historicalla_addresses do
    'https://stark-cove-20051.herokuapp.com/street_list/' # street_list implemented in historicLA since streets goes to crores/streets which is different
  end

  resources :users
  resources :sessions # for logging in. p337
  resources :account_activations, only: %i[edit]
  resources :password_resets, only: %i[new create edit update]
  resources :resto_resid_lines
  resources :lines, controller: 'resto_resid_lines' # alternate /url
  resources :images # do I need this anymore?

  # From Clark, but too crude. See below for what I need to do
  # resources :map
  get 'map', to: 'map#index' # leaftlet version of map

  # The following are for OpenLayers. Some are development
  get 'olMap', to: 'map#olMap' # ol version of map
  get 'openlayers', to: 'map#ol'
  get 'ol', to: 'map#ol'
  get 'olls', to: 'map#ol_layer_switcher'
  get 'layerswitcher', to: 'map#ol_layer_switcher'
  get 'geojson_features', to: 'map#geojson_features'
  get 'geojsonFromFile', to: 'map#geojsonFromFile'
  get 'leafletSelfContained', to: 'map#leaflet_self_contained'
  get 'leafletSelfContainedMapDiv2', to: 'map#leafletSelfContainedMapDiv2'
  get 'allLocations', to: 'locations#allLocations' # had the html.erb in /map but /location seems more logical

  # jBuilder needs the following. FIXME need to see if all of these are still being used
  get 'map/map_data', defaults: { format: 'json' } # using point_data and line_data now. NO, still needed for something.
  get 'map/dot_data', defaults: { format: 'json' }
  get 'map/line_data', defaults: { format: 'json' }
  get 'map/line_point_data', defaults: { format: 'json' } # combining lines and points
  get 'map/point_data', defaults: { format: 'json' }
  get 'locations/allLocations', defaults: { format: 'json' }
end

app/controllers/years_controller.rb
class YearsController < ApplicationController
  # binding.pry
  helper_method :sort_column, :sort_direction
  before_action :set_year, only: %i[show edit update destroy] # 2019.06.20 Can't see that this is being used anywhere. But without it get an error on years/show.html.erb:5 undefined method `person' for nil:NilClass. This is some basic Rails thing
  before_action :set_s3_direct_post, only: %i[new edit create update] # 2019.06.20 Causing an error if commented out on years/312/edit, but OK as long as aws.rb still set See TODO.md. I also have this in Users. Where does it belong.
  before_action :dup_check, only: %i[new edit update] # runs, but not what I think I want
  before_action :resto_or_resid, only: %i[update] # create is handled within def create

  PAGE_SIZE = 10

  # GET /years/new # First since change frequently
  def new
    puts '=+=+=+= years_controller:12'
    @year =
      Year.find_by(id: params[:base_id])&.dup ||
        Year.new({ year_date: '1896-05-01' })

    # https://stackoverflow.com/questions/61722805/rails-to-for-a-duplicate-record. First statement is for duplicate a record
    puts "=+=+=+= years_controller:15. @year: #{@year}. @year.year_date: #{
           @year.year_date
         }"

    # All from Tutorial Points Tutorial. Second statement for initial value.
    # @year = Year.new({:year_date => "1913-01-01"}) # This is default. Helps to change when going through a group.
    @locations = Location.all
    @people = Person.all
    # @source    = Source.all  # FIXME? this or the change in model
    # year       = Year.new # ActiveStorage
    # @positions = Position.all # The table with titles for people, Errors when new is called. Try again after creating model
    # @full_names = Person.all.given_name + Person.all.last_name
    # binding.pry
  end

  def index
    @search = Year.ransack(params[:q]) # sometimes defined as @q
    @years = @search.result.includes(:location, :person) # this allows associations in ransack
    respond_to do |format|
      format.html {}
      format.json { render json: @years }
    end

    # For Stimulus search
    # https://medium.com/swlh/build-a-dynamic-search-with-stimulus-js-and-rails-6-56b537a44579
    # Fields searched are set in location.rb
    if params[:query]
      @years = Year.global_search(params[:query])
    else
      @years = Year.all
    end
    respond_to do |format|
      format.html
      format.json { render json: { years: @years } }
    end

  end

  # Ransack https://github.com/ylankgz/InvoiceApp
  def search
    index
    render :index
  end

  def documents
    @years = Year.all
  end

  def map_one
    # mapping one connection/year
    # need to use the year passed in and then make it for a year
    years = Year.where(year_date: '1883-09-01'..'1995-12-31')
  end

  def summary
    @years = Year.order(:year_date)
    respond_to do |format|
      format.html {}
      format.json { render json: @years }
    end
  end

  def show
    @year = Year.find(params[:id])
    @doc = Doc.new
  end

  # GET /years/1/edit
  def edit
    # @positions = Position.all # Needed for Positions/ Titles list to work, However not added to database. 2021.07.01 Seems to work without this? But commenting it out doesn't solve the double GET
  end

  # POST /years
  # POST /years.json
  def create
    @year = Year.new(year_params)

    # Below sets resto or resid true/false as needed determined by title (position)
    resto_or_resid # I think the above sets up @year and then this call can work. It doesn't as a before_action
    respond_to do |format|
      if @year.save
        format.html do
          redirect_to @year, notice: 'Connection was successfully created.'
        end # default

        # format.html do
        #   render :edit, notice: 'Connection was partially created. Add snippet.'
        # end # Want to draw snippet. Crude and causing issues
        format.json { render :show, status: :created, location: @year }
      else
        format.html { render :new }
        format.json { render json: @year.errors, status: :unprocessable_entity }
      end
    end
    repopulateResidResto
    # redirect_to year # https://edgeguides.rubyonrails.org/action_text_overview.html but didn't have it before. Already done by something else
  end

  # PATCH/PUT /years/1
  # PATCH/PUT /years/1.json
  def update
    respond_to do |format|
      if @year.update(year_params)
        format.html do
          redirect_to @year, notice: 'Connection was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @year }
      else
        format.html { render :edit }
        format.json { render json: @year.errors, status: :unprocessable_entity }
      end
    end
    repopulateResidResto # nice to have some error handling here
  end

  # DELETE /years/1
  # DELETE /years/1.json
  def destroy
    @year.destroy
    respond_to do |format|
      format.html do
        redirect_to years_url, notice: 'Connection was successfully destroyed.'
      end
      format.json { head :no_content }
    end
    repopulateResidResto
  end

  # https://gorails.com/forum/how-do-i-create-a-delete-button-for-images-uploaded-with-active-storage
  def delete_image_attachment
    @document = ActiveStorage::Attachment.find(params[:id])
    @document.purge
    redirect_back(fallback_location: request.referer)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_year
    # See notes near top for why this is here
    # puts "years_controller:141. :id #{@year.id}"
    @year = Year.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  # Note that I copied all of these to create
  def year_params
    params
      .require(:year)
      .permit(
      :year_date,
      :person_id,
      :name_shown,
      :title,
      :location_id,
      :resid,
      :resto,
      :resto_name,
      :resto_event,
      :notes,
      :content,
      :content_plain_text,
      :doc_id,
      :snippet_extent,
      :snippet_coords
    ) # doc_ids:[] trying for multiples. :file_basename, :notes, :aws_url, :from_where_url, :from_where, :caption, added 2021 although already in db, but not adding anymore? took back out since didn't help. :notes is now in :content, I guess leaving it in since use a a clipboard
  end

  # https://devcenter.heroku.com/articles/direct-to-s3-image-uploads-in-rails or was it Paperclip since this doesn't look like the heroku article. 2019.06.20 Commented out since gave an error. But i may want direct post at some point FIXME deprecated with docs
  def set_s3_direct_post
    @s3_direct_post =
      S3_BUCKET.presigned_post(
        key: "uploads/#{SecureRandom.uuid}/${filename}",
        success_action_status: '201',
        acl: 'public-read'
      )
    puts "=+=+=+= years_controller:141. set_s3_direct_post: #{@s3_direct_post}"
  end

  def dup_check
    # 2020.02.08 This is info only for development. Had to give up as all seems to be handled in controller>create and I won't be able to parse that. Can delete if also remove related before_action from from near top
    # 1. Need to calc checksum of document selected
    # 2. Check if that checksum exists in blobs.
    # 3. If it doesn't continue
    # 4. If it does exist, need to change or write to new active_storage_attachments with the exising blob_id

    # Would be nice to see what instance variable are available, but Black-Leo creates an instance
    # puts "years_controller:70. model.year_date: #{model.year_date}" # trying some Ruby-Copeland p345, but not getting it
    # puts self.caption.downcase # undefined method caption. See previous line
    # puts "years_controller:150. in def dup_check. @year: #{@year}.  @year.id: #{@year.id}" # error on new
    if @year == ''
      # nil didn't work
      puts "=+=+=+= years_controller:156. @year.year_date: #{@year.year_date}" # trying some Ruby-Copeland p345, but not getting it

      io =
        '/Users/gscar/Documents/Genealogy/1900-09 Los Angeles City Directories/1900 NOT Los Angeles City Directory. p902. Restaurants. Restovich, 505 S Main.jpg'

      # io = @tempfile # @tempfile shows up in iTerm, but gives an error, obviously doesn't exist when compile this page
      new_file_checksum = Digest::MD5.file(io).base64digest
      aws_checksum = ActiveStorage::Blob.find_by(checksum: new_file_checksum)
      if aws_checksum
        aws_blob_id =
          ActiveStorage::Blob.find_by(checksum: new_file_checksum).id # the id of the blob that already exists

        # The following is just for dev
        # aws_file_key =  ActiveStorage::Blob.find_by(checksum: new_file_checksum).key
        aws_file_filename =
          ActiveStorage::Blob.find_by(checksum: new_file_checksum).filename

        # aws_file_content_type = ActiveStorage::Blob.find_by(checksum: new_file_checksum).file_content_type
        # aws_file_metadata = ActiveStorage::Blob.find_by(checksum: new_file_checksum).file_metadata
        # aws_file_byte_size = ActiveStorage::Blob.find_by(checksum: new_file_checksum).file_byte_size
        # aws_file_created_at = ActiveStorage::Blob.find_by(checksum: new_file_checksum).file_created_at
        puts "years_controller:190. searched and found that a blob for checksum: #{
               new_file_checksum
             } and need to do other stuff" # works with link to a file as in the first test
        puts "id of already existing file at AWS, named aws_blob_id: #{
               aws_blob_id
             }. Will become blob_id in active_storage_attachments for new entry"
        puts "years_controller:192. Now need to find how to write to active_storage_attachments for year.id #{
               @year.id
             } changing the blob_id to #{
               aws_blob_id
             } since it already exist. And not create the blob!!! Maybe it's for me to do the save or update from scratch?"

app/helpers/years_helper.rb
module YearsHelper
end

app/views/years/_form_action_text_test.html.erb
<!-- This can be used to see if a problem with simple_form, i.e., this isn't using simple form. -->
<%= form_with(model: @year) do |form| %>
  <div class="field">
    <%= form.label :content %>
    <%= form.rich_text_area :content %>
  </div>
<% end %>
Getting the small box, just like with simple_form 2020.09.12

app/views/years/_form_bootstrap.html.erb
<!-- It's either this or _form.html.erb as an option This one depends on bootstrap and gem bootstrap_form

https://github.com/bootstrap-ruby/bootstrap_form
https://github.com/bootstrap-ruby/bootstrap_form/issues/554 -->
<!-- https://apidock.com/rails/v6.0.0/ActionView/Helpers/FormOptionsHelper/collection_check_boxes -->

<%= bootstrap_form_for(@year) do |f| %>
  <%= f.text_field :resid %>
  <%= f.check_box :resto %>
  <%= fields_for :location, @year.location do |location_form| %>
    <%= location_form.text_field :address %>
  <% end %>
  <%= f.submit "Create/Update Connection" %>
<% end %>

app/views/years/_select_docs_notes.html.erb
<!-- Copied from views/layouts/_select_docs_notes.html.erb. Deleted all notes, but look at it if this needs to be changed -->
<%= form.association :doc, label_method: :id_page, collection: Doc.all, value_method: :id, label: "Select document(s) that support this" %>

<%= form.label :snippet_coords, "Snippet_coords will appear when snippet is drawn" %>
<%= form.text_area :snippet_coords, as: :text, rows: 4 %>

<div class="notes well well-sm">
  <%= form.label :content, "Notes. [Do not attach documents here since already have above. Otherwise end up with multiple copies?]:" %>
  <%= form.rich_text_area :content, rows: 6, value: "Testing, add your own content"  %>
</div>

<!-- Don't show the field if it's empty -->
<% if @year.notes.present? %>
  <div>
    <%= form.label :notes, "Notes (deprecated). Transfer to above" %>
    <%= form.text_area :notes, as: :text, rows: 5 %>
  </div>
<% end %>

app/views/years/_year.html.erb
<!-- in location > show Lists the people and their connection to the address via <%#= render @location.years %> -->
<!-- Also being used by allLocations.html.erb ? -->
<!-- works from locations/show but doesn't from docs/show edit so need to make a different on or render -->
<li id="year-<%= year.id %>" class="doc-item-detail"> <!-- id: Read more of Hartl to find out what this is for, but seems to work without. class if for Turbo showing on show/docs page -->

  <!-- A flag if 1890 doesn't match, but misleading for addresses for which it doesn't matter -->
   <span>
    <%# if (year.year_date.to_s < "1890-01-01") && @location.pre1890  ||  (year.year_date.to_s >= "1890-01-01") && @location.pre1890 == false %> <!-- Didn't work numerically -->
      <!-- # --><!-- OK -->
    <%# else %>
      <!-- #<strong>Address may not be for same period as this item!</strong> -->
    <%# end %>
  </span>
  <%#= @doc.source.effective_date === year.year_date %>

<!-- FIXME doesn't work here no @doc -->
  <span class="<%#= (@doc.source.effective_date === year.year_date) ? "year_date" : "year_date text-danger" %>"><strong><%= year.year_date.strftime('%Y') %></strong> <%= year.year_date.strftime(' ' '%b' ' ' '%-d') %>:</span> <!-- The class Highlighting if dates don't match, but not working at the moment -->
  <span class="text-success"><%= year.person.full_name %>.</span>
  <% if year.name_shown? %>
    <span class="text-secondary"> (<%= year.name_shown %>).</span>
  <% end %>
  <span><%= year.title %> at </span>
  <!-- <span class="res"><%= year.resto ? 'Restaurant.': '' %> <%= year.resid ? 'Residence.': '' %></span> -->
  <span class="address"><%= year.resto_name ?  year.resto_name : '' %></span>
  <span><%= year.location.address %>.</span>
  <span class="btn btn-outline-success btn-xs"><%= link_to 'Show', year %></span>
  <span class="btn btn-outline-warning btn-xs"><%= link_to 'Edit', edit_year_path(year) %></span>
</li>

app/views/years/index.html.erb
<!-- years/index.html.erb -->
<p id="notice"><%= notice %></p>
<% provide(:title, 'Connections') %>
<h1>Connections&mdash;Where a Person Was On a Particular Date (<%= @years.count %>)</h1>

  <div class="col-md-12 h4">Each line is one data point, that is, where a person either lived or worked on a particular date. In other words, some of the raw data. If where a person worked and lived at the same point in time is known it is <%= link_to ' shown here', resto_resid_lines_path %>. The data is scattered enough that this information is not known for very many people.
  </div>

<!-- <%#= render 'newcon' %> Included in Ransack line .At bottom of page now-->

<!-- Ransack and https://github.com/ylankgz/InvoiceApp -->
<div class="container-fluid">
  <div class="col-md-2">
  <div class="btn btn-primary "> 
    <%= link_to 'Add New Connection', new_year_path %> 
  </div></div>

  <!-- Ransack search, see years_controller Only on dates now and is too complicated -->
  <!-- <%= search_form_for @search, url: search_years_path, html: {class: "form-inline col-md-8 col-md-offset-1", method: :post} do |f| %> -->
    <!-- <div class="input-daterange"> --> <!-- not using class. Needed for datepicker -->
      <!-- <div class="col-md-3">
        <%= f.text_field :year_date_gteq, class: "form-control search-field", placeholder: "Date from '1905-08-30'" %>
      </div>  --><!-- gteq is greater than or equal. lteq is less than or equal in ransack -->
      <!-- <div class="col-md-3 col-md-offset-1">
        <%= f.text_field :year_date_lteq, class: "form-control search-field", placeholder: "Date to '1906-08-28'" %>
      </div>
    </div>
    <div class="col-md-2 col-md-offset-1 form-actions">
      <%= f.submit "Search", class: "btn btn-success" %>
    </div>
    <div class="btn btn-primary ">  -->
      <!-- <%= link_to 'Clear search', years_path %>
    </div>
  <% end %>
</div>  --><!-- end ransack search and new -->

<!-- Stimulus search -->
<!-- https://medium.com/swlh/build-a-dynamic-search-with-stimulus-js-and-rails-6-56b537a44579 -->
<div class="container">
  <div class="row justify-content-center" data-controller="search-years">
    <div class="col-xs-12 col-sm-6 border rounded-pill border-3 p-2">
      <!-- <h5>Search... <em>on all but ActiveText!</em></h5> -->
      <!-- Can change the fields in model/year.rb -->
      <%= @years.count %> found. 
      <%= form_with(url: years_path, method: :get, class:"d-lg-inline-flex mt-2 mt-md-0", data: {action: "submit->search#submit"}) do |f| %> <!-- Class is mine, not demo and formats the Search button only -->
        <%#= label_tag(:query, "Search for") %>
        <%= text_field_tag :query, params[:query], data: {target: "search.query"}, class: "form-control mr-sm-2", placeholder: "Connection search:" %>
        <%= submit_tag("Search", class: "btn btn-primary") %>
      <% end %>
      <%= link_to "Show all", years_path, class: "btn btn-outline-warning my-2 my-sm-0" %> <!-- Need to hide this when all are showing TODO -->
    </div>
  </div>
</div>
<br>

<table class="years pretty table table-striped table-hover table-responsive">
  <thead>
      <tr>
        <th><%= sort_link(@search, :id, "ID") %></th>
        <th>Res or Resto</th>
        <th><%= sort_link(@search, :year_date, "Date") %></th> <!-- , default_order: :asc doesn't seem to be needed -->
        <th class="center"><%= sort_link(@search, :person_id, "Person ID") %></th>
        <th class="text-right">Given</th>
        <th><%= sort_link(@search, :person_last_name, [:person_last_name, 'person_given_name asc'] ) %></th>
        <!-- , %i(person_last_name person_first_name),
                  default_order: { person_last_name: 'asc', person_given_name: 'asc' } -->
  <!--Can't combine into full_name_id because then couldn't sort on last_name -->
        <th>Title</th>
        <!-- <th class="center">< = sort_link @search, : "location_id",   "Address ID" %></th> Leaving this in case need to see it temporarily-->
        <th><%= sort_link @search, :location_address, "Address" %></th>
        <th>Doc ID [Need doc title like show  FIXME]</th>
        <!-- <th>Image</th> -->
        <th>Notes</th>
        <!-- <th>< = sort_link @search, : "year.updated_at", "Updated UTC" %></th> Leaving this in case need to see it temporarily- -->
        <% if logged_in? %>
          <th colspan="4"></th>
        <% else %>
          <th>Details</th>
        <% end %>
      </tr>
  </thead>

  <tbody class="locations">
    <% @years.each do |year| %>
       <tr class= <%= year.resid ? "resid" : "resto" %>>
          <td><%= year.id %></td>
          <td class="center"><%= year.resto ? 'Restaurant' : '' %> <%= year.resid ? 'Residence' : '' %><i> <%= year.resto_name ? year.resto_name : '' %></i></td>
          <td><%= year.year_date %></td>
          <td class="center link-blue"><%= link_to(year.person) do %><%= year.person_id %><% end %></td>
          <td class="text-right link-blue"><%= year.person.try(:given_name) %></td>
          <!-- Link doesn't work if wrap all three person related fields (id, first, last) Can't even wrap one field if put td's inside the do-->
          <!--Can't combine into full_name_id because then couldn't sort on last_name -->
          <td class="link-blue"> <%= link_to(year.person) do %> <%= year.person.try(:last_name) %><% end %></td>
          <td><%= year.title %></td>
          <!-- <td class="center">< = year.location_id %></td> -->
          <td class="link-blue"><%= link_to(year.location) do %> <%= year.location.try(:address) %> <% end %></td> <!-- < = year.location.try(:city)=="Los Angeles" ? '' : year.location.try(:city) %> -->
          <td><%= year.doc_id %></td>
          <!-- <td> -->
            <!-- <div class="media media-right">
              <a href="<%#= year.aws_url %>">
                <img class="media-object" src="<%#= year.aws_url %>" height="50" width="50">
              </a> -->
              <!--TODO How to get active_storage image here, below is from show, but document isn't necessarily meaningful -->
              <!-- < = link_to image_tag(year.document.variant(resize: "50x50")), document %> -->
            <!-- </div> -->
          <!-- </td> -->
          <td><%= year.content %><%= year.notes %></td>
          <!-- <td>< = year.updated_at.strftime('%d' ' ' '%b' ' ' '%Y'', ' '%H'':''%H') %></td>  -->

          <!-- But this creates many #index and only one per page is allowed -->
          <td><%= link_to 'Show details', year %></td>

          <% if logged_in? %>
             <td><%= link_to 'Edit', edit_year_path(year) %></td>
             <td><%= link_to 'Destroy', year, method: :delete, data: { confirm: 'Are you sure you want to delete year.id FIXME' } %></td>
          <% end %>
       </tr>
    <% end %>
  </tbody>
</table>
<br/> <!-- !render bookmark -->
<%= render 'newcon' %>

app/views/years/summary.html.erb
<!--years summary.html.erb -->
<p id="notice"><%= notice %></p>
<% provide(:title, 'Summary') %>
<h1>Summary of Dates, People and Places (<%= @years.count %>)</h1>
<div class="row">
  <div class="col-md-12 h4">A more detailed list is <%= link_to ' available here', years_path %> or click on each item for more details of that item. This is a list of every person to place connection for both restaurants and residences. This is much of the data I have up to 1899. Data beyond then will be added.</div>
</div>
<div class="row">
  <div class="col-md-12 h4">A list of people with their work (restaurant) and home address at a point in time is <%= link_to ' shown here', resto_resid_lines_path %>. In other words this is useful for finding people who knew each other.</div>
</div>
<div class="row summary">
  <div class="col-md-12 h5">Dates Sep-01-xxxx are an estimated date for the effective date in a City Directory dated the following year, e.g., Sep 01 1886 is from the 1887 directory. Names and addresses can be clicked for more information on the item.</div>
</div>
<!-- Maybe try Bootstrap Grids to control widths better -->
<% @years.each do |year| %>


	<div class= <%= year.resto ? "resto" : "resid" %>>
  <div class="row summary">
    <div class="col-md-4">  On <%= year.year_date.strftime('%b' ' ' '%d' ' ' '%Y') %>, <%= link_to(year.person) do %> <strong><%= year.person.try(:full_name) %></strong> <% end %> was a  <strong><%= year.title %> </strong> at</div>
    <div class="col-md-4"> <strong> <%= link_to(year.location) do %> <%= year.location.try(:address) %><% end %>, <%= year.location.try(:city) %> </strong> which was a</div>
    <div class="col-md-3"> <strong> <%= year.resto ? 'restaurant' : '' %> <%= year.resto_name? ? " named \"#{year.resto_name}\" " : '' %> <%= year.resid ? 'residence' : '' %> </strong> </div>
	  <div class="col-md-1"> <%= link_to 'Details', year %> </div>
  </div></div>
<% end %>

<br/> <!-- !render bookmark -->
    <%= render 'newcon' %>
<p>Dates Sep-01-xxxx are an estimated date for the data in a City Directory dated the following year.</p>